packages:
  - 'apps/*'
  - 'services/*'
  - 'packages/core/*'
  - 'packages/platform/*'
  - 'packages/domains/*'

overrides:
  ua-parser-js: 1.0.39
  prismjs: '>=1.30.0'
  markdown-it: '>=12.3.2'
  serialize-javascript: '>=7.0.3'
  '@xmldom/xmldom': 0.8.12
  fast-xml-parser: '>=5.7.0'
  postcss: '>=8.5.10'
  uuid: '>=11.1.1'
  axios: '>=1.15.1'
  fast-xml-builder: '>=1.1.6'
  kysely: '>=0.28.17'
  '@protobufjs/utf8': '>=1.1.1'
  protobufjs: '>=7.5.6'

nodeVersion: 24.14.1
engineStrict: true
pmOnFail: error
dedupePeerDependents: true
resolvePeersFromWorkspaceRoot: true
verifyStoreIntegrity: true
strictStorePkgContentCheck: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: true
  msgpackr-extract: false
  msw: false
  protobufjs: false
  unrs-resolver: true
