import type { InboxStreamItem } from './inbox-stream-items'

export const MOCK_INBOX_STREAM_ITEMS: InboxStreamItem[] = [
  {
    id: 'mock-note-1',
    kind: 'note',
    title: 'Trip notes for Ojai reset weekend',
    preview: 'Weekend planning',
    timestamp: '2026-03-19T08:45:00.000Z',
    route: '/(protected)/(tabs)/focus',
  },
  {
    id: 'mock-chat-1',
    kind: 'chat',
    title: 'Morning planning with Sherpa',
    preview: 'Action plan',
    timestamp: '2026-03-19T08:22:00.000Z',
    route: '/(protected)/(tabs)/sherpa?chatId=mock-chat-1',
  },
  {
    id: 'mock-note-2',
    kind: 'note',
    title: 'Draft announcement for the universal composer rollout',
    preview: 'Launch draft',
    timestamp: '2026-03-19T07:55:00.000Z',
    route: '/(protected)/(tabs)/focus',
  },
  {
    id: 'mock-chat-2',
    kind: 'chat',
    title: 'Rewrite this note into a tighter product brief',
    preview: 'Rewrite request',
    timestamp: '2026-03-19T07:20:00.000Z',
    route: '/(protected)/(tabs)/sherpa?chatId=mock-chat-2',
  },
  {
    id: 'mock-note-3',
    kind: 'note',
    title: 'People to follow up with after Tuesday design review',
    preview: 'Follow-up list',
    timestamp: '2026-03-18T19:10:00.000Z',
    route: '/(protected)/(tabs)/focus',
  },
  {
    id: 'mock-chat-3',
    kind: 'chat',
    title: 'Summarize all open ideas from this week',
    preview: 'Weekly summary',
    timestamp: '2026-03-18T18:36:00.000Z',
    route: '/(protected)/(tabs)/sherpa?chatId=mock-chat-3',
  },
  {
    id: 'mock-note-4',
    kind: 'note',
    title: 'Attachment-heavy capture from the vendor packet review',
    preview: 'Vendor review',
    timestamp: '2026-03-18T16:02:00.000Z',
    route: '/(protected)/(tabs)/focus',
  },
]
