export type {
  NotesListInput,
  NotesListOutput,
  NotesGetOutput,
  Note,
  NotesCreateInput,
  NotesCreateOutput,
  NotesUpdateInput,
  NotesUpdateOutput,
  NotesDeleteOutput,
  NotesSyncItem,
  NotesSyncInput,
  NotesSyncOutput,
  GoalListOutput,
  GoalGetOutput,
  GoalCreateInput,
  GoalCreateOutput,
  GoalUpdateInput,
  GoalUpdateOutput,
  GoalDeleteOutput,
  GoalArchiveOutput,
  Goal,
} from '@hominem/hono-rpc/types';
