export {
  parseAmount,
  calculateMedian,
  formatCurrency,
  aggregateByCategory,
  aggregateByMonth,
  aggregateByAccount,
  calculateTransactionStats,
  calculatePercentageChange,
  calculateTrend,
  groupTransactionsByDateRange,
} from './analytics/aggregation.service';
export { calculateAveragePerDay, calculateTimeSeriesTotals } from './analytics/analytics.utils';
export {
  type TimeSeriesDataPoint,
  type TimeSeriesStats,
  type TimeSeriesResponse,
  generateTimeSeriesData,
  calculateTimeSeriesStats,
} from './analytics/time-series.service';
export {
  type CategorySummary,
  summarizeByCategory,
  type MonthSummary,
  summarizeByMonth,
  findTopMerchants,
  type TransactionStats,
  type TransactionAggregation,
  calculateTransactions,
  type MonthlyStatsOutput,
  getMonthlyStats,
} from './analytics/transaction-analytics.service';
export {
  type BudgetCategoryBase,
  type BudgetCategoryWithSpending,
  type BudgetSummary,
  type BudgetTrackingData,
  type BudgetChartData,
  type BudgetPieData,
} from './budget.types';
export { deleteAllFinanceData } from './cleanup.service';
export {
  createAccount,
  createManyAccounts,
  listAccounts,
  getAccountById,
  findAccountByNameForUser,
  updateAccount,
  deleteAccount,
  getAndCreateAccountsInBulk,
  getBalanceSummary,
  listAccountsWithRecentTransactions,
  getAccountWithPlaidInfo,
  listAccountsWithPlaidInfo,
  listPlaidConnectionsForUser,
  listInstitutionConnections,
  getAccountsForInstitution,
  validateAccountNameUnique,
  validateAccountExists,
  linkAccountToInstitution,
  unlinkAccountFromInstitution,
  AccountsService,
} from './features/accounts/accounts.service';
export {
  AccountDomainSchema,
  CreateAccountSchema,
  UpdateAccountSchema,
  AccountWithPlaidInfoSchema,
  BalanceSummarySchema,
  PlaidConnectionSchema,
  InstitutionConnectionSchema,
  type FinanceAccountOutput,
  type CreateAccountInput,
  type UpdateAccountInput,
  type AccountWithPlaidInfo,
  type BalanceSummary,
  type PlaidConnection,
  type InstitutionConnection,
} from './features/accounts/accounts.domain';
export { AccountsRepository } from './features/accounts/accounts.repository';
export { CHART_COLORS, getBudgetStatus, getStatusColor, getChartColor } from './core/budget.utils';
export {
  getTransactionCategoriesAnalysis,
  bulkCreateBudgetCategoriesFromTransactions,
} from './core/budget-analytics.service';
export {
  type BudgetCategoryType,
  getBudgetCategories,
  getBudgetCategorySuggestions,
  getSpendingCategories,
  createBudgetCategory,
  updateBudgetCategory,
  deleteBudgetCategory,
  getBudgetCategoryById,
  checkBudgetCategoryNameExists,
  getUserExpenseCategories,
  getAllBudgetCategories,
} from './core/budget-categories.service';
export {
  getBudgetGoals,
  createBudgetGoal,
  updateBudgetGoal,
  deleteBudgetGoal,
} from './core/budget-goals.service';
export {
  getBudgetCategoriesWithSpending,
  calculateBudgetSummary,
  generateChartData,
  generatePieData,
  getBudgetTrackingData,
} from './core/budget-tracking.service';
export { InstitutionsRepository } from './core/institutions.repository';
export {
  getInstitutionById,
  getAllInstitutions,
  createInstitution,
  getUserPlaidItemForInstitution,
  InstitutionService,
} from './core/institution.service';
export {
  calculateRunway,
  type RunwayCalculationResult,
  type RunwayCalculationInput,
  runwayCalculationSchema,
} from './core/runway.service';
export {
  CategoryBreakdownSchema,
  getCategoryBreakdownInputSchema,
  getCategoryBreakdownOutputSchema,
  getSpendingTimeSeriesInputSchema,
  getSpendingTimeSeriesOutputSchema,
  getTopMerchantsInputSchema,
  getTopMerchantsOutputSchema,
  type GetCategoryBreakdownOutput,
  getCategoryBreakdown,
  type GetSpendingTimeSeriesOutput,
  getSpendingTimeSeries,
  type GetTopMerchantsOutput,
  getTopMerchants,
} from './finance.analytics.service';
export {
  calculateBudgetBreakdown,
  calculateSavingsGoal,
  calculateLoanDetails,
  calculateBudgetBreakdownInputSchema,
  calculateBudgetBreakdownOutputSchema,
  calculateSavingsGoalInputSchema,
  calculateSavingsGoalOutputSchema,
  calculateLoanDetailsInputSchema,
  calculateLoanDetailsOutputSchema,
} from './finance.calculators.service';
export {
  SuccessResponseSchema,
  createFinanceAccountInputSchema,
  getFinanceAccountsInputSchema,
  getFinanceAccountsOutputSchema,
  updateFinanceAccountInputSchema,
  deleteFinanceAccountInputSchema,
  deleteFinanceAccountOutputSchema,
} from './finance.schemas';
export {
  createFinanceAccountDef,
  createFinanceAccountServer,
  getFinanceAccountsDef,
  getFinanceAccountsServer,
  updateFinanceAccountDef,
  updateFinanceAccountServer,
  deleteFinanceAccountDef,
  deleteFinanceAccountServer,
  createTransactionDef,
  createTransactionServer,
  getTransactionsDef,
  getTransactionsServer,
  updateTransactionDef,
  updateTransactionServer,
  deleteTransactionDef,
  deleteTransactionServer,
  getSpendingCategoriesDef,
  getSpendingCategoriesServer,
  getCategoryBreakdownDef,
  getCategoryBreakdownServer,
  getSpendingTimeSeriesDef,
  getSpendingTimeSeriesServer,
  getTopMerchantsDef,
  getTopMerchantsServer,
  calculateBudgetBreakdownDef,
  calculateBudgetBreakdownServer,
  calculateRunwayDef,
  calculateRunwayServer,
  calculateSavingsGoalDef,
  calculateSavingsGoalServer,
  calculateLoanDetailsDef,
  calculateLoanDetailsServer,
  getBudgetCategoriesInputSchema,
  getBudgetCategoriesOutputSchema,
  getBudgetCategoriesDef,
  getBudgetCategoriesServer,
  calculateTransactionsInputSchema,
  calculateTransactionsOutputSchema,
  calculateTransactionsDef,
  calculateTransactionsServer,
  tools,
} from './finance.tool-servers';
export {
  getTransactionsInputSchema,
  getTransactionsOutputSchema,
  updateTransactionInputSchema,
  updateTransactionOutputSchema,
  deleteTransactionInputSchema,
  deleteTransactionOutputSchema,
  queryTransactionsOutputSchema,
  type QueryTransactionsOutput,
  buildWhereConditions,
  queryTransactions,
  getTransactions,
  findExistingTransaction,
  createTransactionInputSchema,
  createTransactionOutputSchema,
  createTransaction,
  createTransactions,
  updateTransactionIfNeeded,
  updateTransaction,
  deleteTransaction,
} from './finance.transactions.service';
export {
  type FinanceAccountInput,
  type Transaction,
  type TransactionInsert,
  type TransactionType,
  type CategoryAggregate,
  type MonthAggregate,
  type TopMerchant,
  type TransactionResult,
  type QueryOptions,
} from './finance.types';

export {
  getPlaidItemByUserAndItemId,
  getPlaidItemById,
  getPlaidItemByItemId,
  getPlaidItem,
  ensureInstitutionExists,
  upsertPlaidItem,
  updatePlaidItemStatusByItemId,
  updatePlaidItemStatusById,
  updatePlaidItemCursor,
  updatePlaidItemSyncStatus,
  updatePlaidItemError,
  deletePlaidItem,
  upsertAccount,
  getUserAccounts,
  getAccountByPlaidId,
  insertTransaction,
  getTransactionByPlaidId,
  updateTransaction as updatePlaidTransaction,
  deleteTransaction as deletePlaidTransaction,
} from './plaid.service';
export {
  type ParsedTransactions,
  parseTransactionStream,
  processTransactionsFromCSVBuffer,
  progressEmitter,
  processTransactionsInBulk,
  getProcessingConfig,
} from './processing';
