/**
 * Curated list of common tech/professional skills for autocomplete suggestions.
 * Kept small — this is a seed set, not an exhaustive dictionary.
 */
export const COMMON_SKILLS = [
  'AWS',
  'Agile',
  'Alpine.js',
  'Android',
  'Angular',
  'Ansible',
  'Apollo',
  'ArgoCD',
  'Astro',
  'Babel',
  'Bash',
  'BootStrap',
  'C',
  'C#',
  'C++',
  'CSS',
  'CSS-in-JS',
  'Chakra UI',
  'CI/CD',
  'Clojure',
  'Cloudflare',
  'CloudFormation',
  'Cobra',
  'Code Review',
  'Confluence',
  'Content Strategy',
  'Copywriting',
  'Cypress',
  'D3.js',
  'DNS',
  'Dart',
  'Datadog',
  'Design Systems',
  'Digital Marketing',
  'Django',
  'Docker',
  'Drizzle',
  'Drupal',
  'Dart',
  'EC2',
  'ESLint',
  'Edge Functions',
  'Elasticsearch',
  'Electron',
  'Elixir',
  'Ember.js',
  'Erlang',
  'Ethereum',
  'Expo',
  'Express',
  'Figma',
  'Firebase',
  'Flask',
  'Flutter',
  'Framer Motion',
  'Frontend',
  'Functional Programming',
  'GO',
  'Gatsby',
  'Git',
  'GitHub Actions',
  'GitLab CI',
  'Go',
  'Google Analytics',
  'Google Cloud',
  'GraphQL',
  'Graphic Design',
  'Groovy',
  'Grunt',
  'Gulp',
  'Haskell',
  'Heroku',
  'Hono',
  'Hotwire',
  'HTML',
  'HTTP',
  'Hadoop',
  'Haskell',
  'Hbase',
  'IPFS',
  'Illustrator',
  'Ionic',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jest',
  'Jira',
  'Joomla',
  'JSON',
  'JWT',
  'K8s',
  'Kafka',
  'Kotlin',
  'Kubernetes',
  'LLM',
  'Laravel',
  'Leadership',
  'Less',
  'Linux',
  'Lua',
  'MUI',
  'Machine Learning',
  'Mailchimp',
  'MariaDB',
  'Material Design',
  'MongoDB',
  'MySQL',
  'NPM',
  'NestJS',
  'Next.js',
  'Nginx',
  'Node.js',
  'NoSQL',
  'Notion',
  'Nuxt',
  'OAUTH',
  'Object Oriented',
  'OpenAI',
  'OpenAPI',
  'OpenShift',
  'Oracle',
  'PMP',
  'PHP',
  'PM2',
  'PNPM',
  'PostCSS',
  'PostgreSQL',
  'Postman',
  'Prettier',
  'Prisma',
  'Product Management',
  'Product Strategy',
  'Prometheus',
  'Prototyping',
  'Pulumi',
  'PyTorch',
  'Python',
  'QA',
  'R',
  'REST',
  'RSpec',
  'RabbitMQ',
  'Rails',
  'React',
  'React Native',
  'React Query',
  'Redis',
  'Redux',
  'Remote Collaboration',
  'Rendering',
  'Rust',
  'S3',
  'SCSS',
  'SCSS',
  'SQL',
  'SQLite',
  'SSR',
  'SST',
  'SWR',
  'SWC',
  'Sass',
  'Scala',
  'Scrum',
  'Selenium',
  'Serverless',
  'Shopify',
  'Svelte',
  'Swagger',
  'Swift',
  'SwiftUI',
  'Tailwind CSS',
  'TanStack Query',
  'TanStack Router',
  'Team Leadership',
  'Tech Writing',
  'Terraform',
  'Three.js',
  'TypeScript',
  'UI Design',
  'UX Research',
  'Unity',
  'Unreal',
  'VB.NET',
  'VSCode',
  'Vercel',
  'Video Editing',
  'Vim',
  'Visual Design',
  'Vitest',
  'Vue.js',
  'Web3',
  'WebAssembly',
  'WebRTC',
  'Webflow',
  'Webpack',
  'WordPress',
  'XML',
  'YAML',
  'Yarn',
  'Zeplin',
  'Zustand',
  'accessibility',
  'a11y',
  'cybersecurity',
  'data analysis',
  'data science',
  'data vizualization',
  'database design',
  'devops',
  'digital strategy',
  'ios',
  'microservices',
  'mobile',
  'performance',
  'responsive design',
  'security',
  'seo',
  'software architecture',
  'storytelling',
  'system design',
  'unit testing',
  'user research',
  'wireframing',
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
