/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'

declare const self: ServiceWorkerGlobalScope

self.skipWaiting()
clientsClaim()

// 1. Precache assets generated by the build
// biome-ignore lint/suspicious/noExplicitAny: <explanation>
const manifest = (self as any).__WB_MANIFEST
if (manifest) {
  precacheAndRoute(manifest)
}

// 2. Clean up old caches
cleanupOutdatedCaches()

// 3. Routing Strategies

// Navigation requests (HTML pages) - Network First
// Tries to get fresh content, falls back to cache if offline
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
)

// Static Assets (Images, Fonts) - Cache First
// Cache images with a 60-day expiration
registerRoute(
  ({ request }) =>
    request.destination === 'image' ||
    request.destination === 'font' ||
    request.url.includes('/favicons/'),
  new CacheFirst({
    cacheName: 'static-assets-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
      }),
    ],
  })
)

// Scripts and Styles - Stale While Revalidate
// Serve cached content while updating in the background
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'worker',
  new StaleWhileRevalidate({
    cacheName: 'assets-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
)

// Data Requests (API) - Network First or StaleWhileRevalidate
// For this app, let's use NetworkFirst for reliability, but allow offline access
registerRoute(
  ({ url }) => url.pathname.startsWith('/api') || url.searchParams.has('_data'),
  new NetworkFirst({
    cacheName: 'data-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
)

// Handle offline fallback for navigation if needed (optional)
// const offlineFallback = '/offline.html'
