/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AppCareerApplicationStageKind = 'APPLICATION' | 'OFFER' | 'OUTCOME' | 'SCREEN';

export type AppCareerApplicationStatus =
  | 'ACCEPTED'
  | 'APPLIED'
  | 'OFFER'
  | 'REJECTED'
  | 'SCREENING'
  | 'WISHLIST'
  | 'WITHDRAWN';

export type AppCareerEngagementKind =
  | 'CONTRACT'
  | 'EMPLOYMENT'
  | 'FREELANCE'
  | 'OTHER'
  | 'VOLUNTEER';

export type AppCareerOfferDecision = 'ACCEPTED' | 'DECLINED' | 'NEGOTIATING' | 'PENDING';

export type AppCareerProjectStatus = 'BACKLOG' | 'CANCELED' | 'DONE' | 'IN_PROGRESS';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  accountId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  scope: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppAiUsageEvents {
  cachedInputTokens: number | null;
  costUsd: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  durationMs: number | null;
  errorCode: string | null;
  errorStatus: number | null;
  feature: string;
  id: Generated<string>;
  inputTokens: number;
  metadata: Json | null;
  model: string | null;
  operation: string;
  outputTokens: number;
  ownerUserid: string;
  provider: string;
  reasoningTokens: number | null;
  requestId: string | null;
  status: Generated<string>;
  totalTokens: number;
  usageAvailable: Generated<boolean>;
}

export interface AppCalendarEventAttendees {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  eventId: string;
  id: Generated<string>;
  personId: string | null;
  role: Generated<string>;
  source: string | null;
}

export interface AppCalendarEvents {
  calendarId: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  endsAt: ColumnType<string, Date | string, Date | string> | null;
  eventType: string | null;
  externalUid: string | null;
  id: Generated<string>;
  isAllDay: Generated<boolean>;
  metadata: Generated<Json>;
  organizer: string | null;
  ownerUserid: string;
  placeId: string | null;
  recurrenceRule: string | null;
  source: string | null;
  sourceRowId: string | null;
  startsAt: ColumnType<string, Date | string, Date | string>;
  status: string | null;
  title: string;
  tripId: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCalendars {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  name: string;
  ownerUserid: string;
}

export interface AppCareerApplicationFiles {
  applicationId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  fileName: string;
  fileType: string | null;
  fileUrl: string;
  id: Generated<string>;
}

export interface AppCareerApplicationNotes {
  applicationId: string;
  content: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
}

export interface AppCareerApplications {
  appliedAt: ColumnType<string, Date | string, Date | string> | null;
  company: string;
  coverLetterUrl: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currentStageId: string | null;
  id: Generated<string>;
  jobPostingUrl: string | null;
  legacyId: string | null;
  location: string | null;
  notes: string | null;
  ownerUserid: string;
  referredBy: string | null;
  resumeUrl: string | null;
  salaryExpectation: number | null;
  source: string | null;
  status: AppCareerApplicationStatus;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerApplicationsOffers {
  applicationId: string;
  baseSalary: number | null;
  bonus: number | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currency: Generated<string | null>;
  decision: Generated<AppCareerOfferDecision>;
  decisionAt: ColumnType<string, Date | string, Date | string> | null;
  equity: string | null;
  id: Generated<string>;
  notes: string | null;
  signingBonus: number | null;
  stageId: string;
  totalComp: number | null;
}

export interface AppCareerApplicationStages {
  applicationId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  enteredAt: ColumnType<string, Date | string, Date | string> | null;
  exitedAt: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  notes: string | null;
  stage: string;
  stageKind: AppCareerApplicationStageKind;
  stageOrder: number;
}

export interface AppCareerCertifications {
  category: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  expirationDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  issueDate: ColumnType<string, Date | string, Date | string> | null;
  issuingOrganization: string;
  isVisible: Generated<boolean>;
  name: string;
  ownerUserid: string;
  positionId: string | null;
  sortOrder: Generated<number>;
  status: Generated<string | null>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerEducation {
  activities: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  degree: string | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  fieldOfStudy: string | null;
  id: Generated<string>;
  notes: string | null;
  ownerUserid: string;
  school: string;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerEngagements {
  address: string | null;
  company: string;
  contactName: string | null;
  contactPhone: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currency: Generated<string | null>;
  description: string | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  isCurrent: Generated<boolean | null>;
  kind: Generated<AppCareerEngagementKind>;
  location: string | null;
  ownerUserid: string;
  reasonForLeaving: string | null;
  salaryHigh: number | null;
  salaryLow: number | null;
  source: Generated<string | null>;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string | null;
}

export interface AppCareerImportJobs {
  attempts: Generated<number>;
  completedAt: ColumnType<string, Date | string, Date | string> | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  draft: Json | null;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  ownerUserid: string;
  progress: Generated<number>;
  queueJobId: string;
  resolvedAt: ColumnType<string, Date | string, Date | string> | null;
  sourceHost: string;
  sourceUrl: string;
  stage: Generated<string>;
  status: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerProfile {
  availabilityStatus: Generated<boolean>;
  birthDate: ColumnType<string, Date | string, Date | string> | null;
  copyright: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  email: string | null;
  firstName: string | null;
  headline: string | null;
  id: Generated<string>;
  industry: string | null;
  initials: string | null;
  isActive: Generated<boolean>;
  isPublic: Generated<boolean>;
  lastName: string | null;
  linkedinUrl: string | null;
  location: string | null;
  openToRemote: Generated<boolean>;
  ownerUserid: string;
  phone: string | null;
  profileImageUrl: string | null;
  registeredAt: ColumnType<string, Date | string, Date | string> | null;
  slug: string | null;
  summary: string | null;
  tagline: string | null;
  title: string | null;
  twitterHandles: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  websites: string | null;
}

export interface AppCareerProjectEngagements {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  engagementId: string;
  ownerUserid: string;
  projectId: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerProjects {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  githubUrl: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  isFeatured: Generated<boolean>;
  isVisible: Generated<boolean>;
  liveUrl: string | null;
  organization: string | null;
  ownerUserid: string;
  shortDescription: string | null;
  sortOrder: Generated<number>;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  status: Generated<AppCareerProjectStatus | null>;
  technologies: Generated<Json>;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  videoUrl: string | null;
}

export interface AppCareerSkills {
  aiDerived: Generated<boolean>;
  category: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  id: Generated<string>;
  isVisible: Generated<boolean>;
  level: number | null;
  name: string;
  ownerUserid: string;
  proof: string | null;
  sortOrder: Generated<number>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  yearsOfExperience: number | null;
}

export interface AppCareerSocialLinks {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  github: string | null;
  id: Generated<string>;
  linkedin: string | null;
  ownerUserid: string;
  twitter: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  website: string | null;
}

export interface AppCareerTestimonials {
  avatarUrl: string | null;
  company: string | null;
  content: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isVerified: Generated<boolean>;
  isVisible: Generated<boolean>;
  linkedinUrl: string | null;
  name: string;
  ownerUserid: string;
  rating: number | null;
  sortOrder: Generated<number>;
  title: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChatGenerationEvents {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  generationId: string;
  id: Generated<string>;
  idempotencyKey: string | null;
  payload: Json;
  sequence: Generated<Int8>;
  type: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChatGenerationRuns {
  assistantMessageId: string | null;
  chatId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  encryptedSnapshot: string | null;
  errorMessage: string | null;
  id: string;
  kind: string;
  ownerUserId: string;
  requestContext: Json | null;
  status: string;
  targetAssistantMessageId: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userMessageId: string | null;
}

export interface AppChatGenerationToolEffects {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  generationId: string;
  id: Generated<string>;
  idempotencyKey: string;
  result: Json;
  toolName: string;
}

export interface AppChatMessages {
  authorUserid: string | null;
  chatId: string;
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  files: Json | null;
  id: Generated<string>;
  parentMessageId: string | null;
  reasoning: string | null;
  role: string;
  toolCalls: Json | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChats {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  lastMessageAt: Generated<ColumnType<string, Date | string, Date | string>>;
  ownerUserid: string;
  primarySpaceId: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChatSources {
  addedByUserid: string | null;
  chatId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  noteId: string;
}

export interface AppChatSpeechRuns {
  characterCount: number;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  lastReconciliationError: string | null;
  messageId: string;
  ownerUserId: string;
  provider: string;
  providerGenerationId: string | null;
  reconciliationAttempts: Generated<number>;
  reconciliationStatus: Generated<string>;
  status: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  usageEventId: string;
}

export interface AppCollectionItems {
  collectionId: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  entityId: string;
  entityTable: string;
  id: Generated<string>;
  note: string | null;
  ownerUserid: string;
  sortOrder: number | null;
}

export interface AppCollectionMembers {
  acceptedAt: ColumnType<string, Date | string, Date | string> | null;
  collectionId: string;
  id: Generated<string>;
  invitedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  invitedEmail: string | null;
  ownerUserid: string;
  personId: string | null;
  role: Generated<string>;
  userId: string | null;
}

export interface AppCollections {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  id: Generated<string>;
  name: string;
  ownerUserid: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  visibility: Generated<string>;
}

export interface AppFiles {
  content: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  metadata: Json | null;
  mimetype: string;
  originalName: string;
  ownerUserid: string;
  size: number;
  storageKey: string;
  textContent: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string;
}

export interface AppFinanceAccounts {
  accountType: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  csvImportKey: string | null;
  currencyCode: Generated<string>;
  id: Generated<string>;
  includeInNetWorth: Generated<boolean>;
  institutionId: string | null;
  lifecycleStatus: Generated<string>;
  mask: string | null;
  metadata: Generated<Json>;
  name: string;
  plaidAccountId: string | null;
  plaidItemId: string | null;
  provider: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceCategories {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceInstitutions {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  logoUrl: string | null;
  name: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppFinanceTransactions {
  accountId: string;
  amount: Numeric;
  categoryId: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currencyCode: Generated<string>;
  description: string | null;
  excluded: Generated<boolean>;
  externalId: string | null;
  id: Generated<string>;
  merchantName: string | null;
  notes: string | null;
  occurredAt: ColumnType<string, Date | string, Date | string> | null;
  pending: Generated<boolean>;
  postedOn: ColumnType<string, Date | string, Date | string>;
  providerPayload: Generated<Json>;
  recurring: Generated<boolean>;
  source: string | null;
  transactionType: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppHealthActivities {
  activityType: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  endsAt: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  metrics: Generated<Json>;
  ownerUserid: string;
  personId: string | null;
  source: string | null;
  startsAt: ColumnType<string, Date | string, Date | string>;
}

export interface AppHealthObservations {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  metadata: Generated<Json>;
  observationType: string;
  observedAt: ColumnType<string, Date | string, Date | string>;
  ownerUserid: string;
  personId: string | null;
  source: string | null;
  unit: string | null;
  value: Numeric | null;
}

export interface AppHealthProfiles {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  heightCm: Numeric | null;
  id: Generated<string>;
  ownerUserid: string;
  personId: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppHealthSupplements {
  category: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  dose: string | null;
  id: Generated<string>;
  notes: string | null;
  ownerUserid: string;
  personId: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppMediaCollectionItems {
  addedAt: ColumnType<string, Date | string, Date | string> | null;
  collectionId: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  mediaItemId: string | null;
  metadata: Generated<Json>;
  position: number | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppMediaCollections {
  collectionType: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  externalId: string | null;
  id: Generated<string>;
  name: string | null;
  ownerUserid: string;
  personId: string | null;
  platform: string | null;
  sortOrder: number | null;
  source: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  visibility: string | null;
}

export interface AppMediaItemActivities {
  activityType: string;
  confidence: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  episode: number | null;
  id: Generated<string>;
  mediaItemId: string | null;
  metadata: Generated<Json>;
  occurredAt: ColumnType<string, Date | string, Date | string>;
  ownerUserid: string;
  personId: string | null;
  provider: string | null;
  rating: Numeric | null;
  rewatchCount: Generated<number>;
  season: number | null;
  starred: Generated<boolean>;
}

export interface AppMediaItemIdentifiers {
  id: Generated<string>;
  identifierType: string;
  identifierValue: string;
  isPrimary: Generated<boolean>;
  mediaItemId: string;
  metadata: Generated<Json>;
  provider: string;
}

export interface AppMediaItems {
  albumId: string | null;
  artistId: string | null;
  author: string | null;
  canonicalTitle: string;
  composer: string | null;
  coverImageUrl: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  dateAddedToLibrary: ColumnType<string, Date | string, Date | string> | null;
  description: string | null;
  discNumber: number | null;
  durationMs: number | null;
  enrichedAt: ColumnType<string, Date | string, Date | string> | null;
  genre: string | null;
  genres: string | null;
  id: Generated<string>;
  lastPlayedAt: ColumnType<string, Date | string, Date | string> | null;
  likeRating: string | null;
  mediaKind: string;
  metadata: Generated<Json>;
  ownerUserid: string;
  playCount: Generated<number>;
  popularity: number | null;
  previewUrl: string | null;
  publicationDate: ColumnType<string, Date | string, Date | string> | null;
  publisher: string | null;
  releaseDate: ColumnType<string, Date | string, Date | string> | null;
  releaseYear: number | null;
  runtimeSeconds: number | null;
  skipCount: Generated<number>;
  source: string | null;
  spotifyId: string | null;
  trackNumber: number | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppMusicAlbums {
  artistId: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  genre: string | null;
  id: Generated<string>;
  ownerUserid: string;
  releaseDate: ColumnType<string, Date | string, Date | string> | null;
  spotifyId: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppNoteFiles {
  attachedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  fileId: string;
  noteId: string;
}

export interface AppNotes {
  content: Generated<string>;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  excerpt: string | null;
  id: Generated<string>;
  kind: Generated<string>;
  ownerUserid: string;
  title: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppOrganizationMemberships {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  organizationId: string;
  ownerUserid: string;
  personId: string;
  source: string | null;
}

export interface AppOrganizations {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppPeople {
  aliases: Generated<Json>;
  birthdate: ColumnType<string, Date | string, Date | string> | null;
  birthplace: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  diet: string | null;
  displayName: string | null;
  education: string | null;
  firstName: string | null;
  id: Generated<string>;
  lastName: string | null;
  location: string | null;
  metadata: Generated<Json>;
  middleName: string | null;
  notes: string | null;
  ownerUserid: string;
  personType: string | null;
  profession: string | null;
  sourceRowId: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppPersonAddressRentHistory {
  contactMethodId: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  effectiveDate: ColumnType<string, Date | string, Date | string>;
  id: Generated<string>;
  ownerUserid: string;
  rentCents: number;
}

export interface AppPersonArtists {
  activeFrom: number | null;
  activeTo: number | null;
  birthPlace: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  discipline: string | null;
  id: Generated<string>;
  movement: string | null;
  name: string;
  nationality: string | null;
  notes: string | null;
  ownerUserid: string;
  personId: string | null;
  sortName: string | null;
  source: Generated<string>;
  spotifyId: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppPersonContactMethods {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  kind: string;
  metadata: Generated<Json>;
  ownerUserid: string;
  personId: string;
  placeId: string | null;
  source: string | null;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  value: string;
}

export interface AppPersonRelationships {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  endedAt: ColumnType<string, Date | string, Date | string> | null;
  fromPersonId: string;
  id: Generated<string>;
  notes: string | null;
  ownerUserid: string;
  relationshipType: string;
  startedAt: ColumnType<string, Date | string, Date | string> | null;
  toPersonId: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppPersonServices {
  category: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  displayName: string | null;
  handle: string | null;
  id: Generated<string>;
  ownerUserid: string;
  personId: string | null;
  platform: string;
  profile: Generated<Json>;
}

export interface AppPlaces {
  city: string | null;
  country: string | null;
  countryCode: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  formattedAddress: string | null;
  geocodedAt: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  placeType: string | null;
  postalCode: string | null;
  sourceRowId: number | null;
  state: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string | null;
}

export interface AppPlaceVisits {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  ownerUserid: string;
  placeId: string | null;
  purpose: string | null;
  source: string | null;
  visitedAt: ColumnType<string, Date | string, Date | string> | null;
}

export interface AppPlaidItems {
  accessToken: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  cursor: string | null;
  errorCode: string | null;
  id: Generated<string>;
  institutionId: string | null;
  lastSyncedAt: ColumnType<string, Date | string, Date | string> | null;
  providerItemId: string;
  status: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppPossessionImages {
  altText: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  displayOrder: Generated<number>;
  id: Generated<string>;
  originalFilename: string | null;
  ownerUserid: string;
  path: string;
  possessionId: string;
}

export interface AppPossessions {
  acquiredDate: ColumnType<string, Date | string, Date | string> | null;
  artDimensions: string | null;
  artistPersonId: string | null;
  artMedium: string | null;
  artMovement: string | null;
  artPeriod: string | null;
  brand: string | null;
  color: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isArchived: Generated<boolean>;
  metadata: Generated<Json>;
  model: string | null;
  name: string;
  netValueCents: number | null;
  notes: string | null;
  ownerUserid: string;
  placement: string | null;
  possessionType: string | null;
  priceCents: number | null;
  retiredDate: ColumnType<string, Date | string, Date | string> | null;
  sellPriceCents: number | null;
  serialNumber: string | null;
  size: string | null;
  status: string | null;
  subCategory: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string | null;
}

export interface AppSocialContacts {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  displayName: string | null;
  externalContactId: string | null;
  id: Generated<string>;
  isMutual: Generated<boolean>;
  kind: string | null;
  metadata: Generated<Json>;
  ownerUserid: string;
  personId: string | null;
  phoneNumber: string | null;
  platform: string;
}

export interface AppSocialEngagements {
  actorId: string | null;
  body: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  engagementType: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  occurredAt: ColumnType<string, Date | string, Date | string>;
  ownerUserid: string;
  platform: string;
  postId: string | null;
  reaction: string | null;
}

export interface AppSocialMessages {
  body: string | null;
  callDurationS: number | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isCall: Generated<boolean>;
  mediaUrl: string | null;
  metadata: Generated<Json>;
  ownerUserid: string;
  senderId: string | null;
  senderName: string | null;
  sentAt: ColumnType<string, Date | string, Date | string>;
  threadId: string;
}

export interface AppSocialPosts {
  caption: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  externalId: string | null;
  id: Generated<string>;
  location: string | null;
  mediaUrl: string | null;
  metadata: Generated<Json>;
  ownerUserid: string;
  platform: string;
  postedAt: ColumnType<string, Date | string, Date | string>;
  postType: string | null;
}

export interface AppSocialThreadParticipants {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  joinedAt: ColumnType<string, Date | string, Date | string>;
  ownerUserid: string;
  personId: string;
  threadId: string;
}

export interface AppSocialThreads {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  externalId: string | null;
  id: Generated<string>;
  isGroup: Generated<boolean>;
  metadata: Generated<Json>;
  ownerUserid: string;
  platform: string | null;
  title: string | null;
}

export interface AppTagAssignments {
  assignmentSource: Generated<string>;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  entityId: string;
  entityTable: string;
  id: Generated<string>;
  removedAt: ColumnType<string, Date | string, Date | string> | null;
  tagId: string;
}

export interface AppTags {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  color: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  name: string;
  ownerUserid: string;
  path: string;
  slug: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTaskParticipants {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  personId: string;
  taskId: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTasks {
  completedAt: ColumnType<string, Date | string, Date | string> | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  dueAt: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  location: string | null;
  ownerUserid: string;
  parentTaskId: string | null;
  primarySpaceId: string | null;
  priority: Generated<string>;
  scheduledEndAt: ColumnType<string, Date | string, Date | string> | null;
  scheduledStartAt: ColumnType<string, Date | string, Date | string> | null;
  schedulingWindowEndAt: ColumnType<string, Date | string, Date | string> | null;
  schedulingWindowStartAt: ColumnType<string, Date | string, Date | string> | null;
  status: Generated<string>;
  timeZone: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTravelSegments {
  arrivesAt: ColumnType<string, Date | string, Date | string> | null;
  confirmationCode: string | null;
  cost: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  departsAt: ColumnType<string, Date | string, Date | string> | null;
  destinationCode: string | null;
  destinationPlaceId: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  originCode: string | null;
  originPlaceId: string | null;
  ownerUserid: string;
  provider: string | null;
  segmentType: string;
  tripId: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTravelTripAttendees {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  personId: string;
  role: string | null;
  tripId: string;
}

export interface AppTravelTrips {
  city: string | null;
  country: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  name: string | null;
  notes: string | null;
  ownerUserid: string;
  price: Numeric | null;
  sourceRowId: number | null;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  state: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppVectorDocuments {
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  embedding: string;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  metadata: Json | null;
  ownerUserid: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface DeviceCode {
  clientId: string | null;
  deviceCode: string;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  lastPolledAt: ColumnType<string, Date | string, Date | string> | null;
  pollingInterval: number | null;
  scope: string | null;
  status: string;
  userCode: string;
  userId: string | null;
}

export interface GooseDbVersion {
  id: Generated<number>;
  isApplied: boolean;
  tstamp: Generated<ColumnType<string, Date | string, Date | string>>;
  versionId: Int8;
}

export interface Jwks {
  alg: string | null;
  createdAt: ColumnType<string, Date | string, Date | string>;
  crv: string | null;
  expiresAt: ColumnType<string, Date | string, Date | string> | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface OauthAccessToken {
  authorizationCodeId: string | null;
  clientId: string;
  confirmation: Json | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  referenceId: string | null;
  refreshId: string | null;
  requestedUserInfoClaims: string | null;
  resources: string | null;
  revoked: ColumnType<string, Date | string, Date | string> | null;
  scopes: string;
  sessionId: string | null;
  token: string;
  userId: string | null;
}

export interface OauthAccessTokenLegacy20260817 {
  accessToken: string;
  accessTokenExpiresAt: ColumnType<string, Date | string, Date | string>;
  clientId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  refreshToken: string;
  refreshTokenExpiresAt: ColumnType<string, Date | string, Date | string>;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthApplicationLegacy20260817 {
  clientId: string;
  clientSecret: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  disabled: Generated<boolean>;
  icon: string | null;
  id: string;
  metadata: string | null;
  name: string;
  redirectUrls: string;
  type: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthClient {
  applicationType: string | null;
  backchannelLogoutSessionRequired: boolean | null;
  backchannelLogoutUri: string | null;
  clientCredentialsScopes: string | null;
  clientDiscoveryId: string | null;
  clientId: string;
  clientSecret: string | null;
  contacts: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  disabled: Generated<boolean>;
  dpopBoundAccessTokens: Generated<boolean>;
  enableEndSession: boolean | null;
  grantTypes: string | null;
  icon: string | null;
  id: string;
  jwks: string | null;
  jwksUri: string | null;
  metadata: Json | null;
  name: string | null;
  policy: string | null;
  postLogoutRedirectUris: string | null;
  redirectUris: string;
  referenceId: string | null;
  requirePKCE: boolean | null;
  responseTypes: string | null;
  scopes: string | null;
  skipConsent: boolean | null;
  softwareId: string | null;
  softwareStatement: string | null;
  softwareVersion: string | null;
  subjectType: string | null;
  tokenEndpointAuthMethod: string | null;
  tos: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  uri: string | null;
  userId: string | null;
}

export interface OauthClientAssertion {
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
}

export interface OauthClientResource {
  clientId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  metadata: Json | null;
  resourceId: string;
}

export interface OauthConsent {
  clientId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  referenceId: string | null;
  requestedUserInfoClaims: string | null;
  resources: string | null;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthConsentLegacy20260817 {
  clientId: string;
  consentGiven: Generated<boolean>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface OauthRefreshToken {
  authorizationCodeId: string | null;
  authTime: ColumnType<string, Date | string, Date | string> | null;
  clientId: string;
  confirmation: Json | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  referenceId: string | null;
  requestedUserInfoClaims: string | null;
  resources: string | null;
  revoked: ColumnType<string, Date | string, Date | string> | null;
  rotatedAt: ColumnType<string, Date | string, Date | string> | null;
  rotationReplayExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  rotationReplayResponse: string | null;
  scopes: string;
  sessionId: string | null;
  token: string;
  userId: string;
}

export interface OauthResource {
  accessTokenTtl: number | null;
  allowedScopes: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  customClaims: Json | null;
  disabled: Generated<boolean>;
  dpopBoundAccessTokensRequired: Generated<boolean>;
  id: string;
  identifier: string;
  metadata: Json | null;
  name: string;
  policyVersion: Generated<number>;
  refreshTokenTtl: number | null;
  signingAlgorithm: string | null;
  signingKeyId: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface Passkey {
  aaguid: string | null;
  backedUp: Generated<boolean>;
  counter: Generated<number>;
  createdAt: ColumnType<string, Date | string, Date | string> | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface RateLimit {
  count: number;
  id: string;
  key: string;
  lastRequest: Int8;
}

export interface Session {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface Verification {
  createdAt: ColumnType<string, Date | string, Date | string> | null;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  identifier: string;
  updatedAt: ColumnType<string, Date | string, Date | string> | null;
  value: string;
}

export interface DB {
  account: Account;
  'app.aiUsageEvents': AppAiUsageEvents;
  'app.calendarEventAttendees': AppCalendarEventAttendees;
  'app.calendarEvents': AppCalendarEvents;
  'app.calendars': AppCalendars;
  'app.careerApplicationFiles': AppCareerApplicationFiles;
  'app.careerApplicationNotes': AppCareerApplicationNotes;
  'app.careerApplications': AppCareerApplications;
  'app.careerApplicationsOffers': AppCareerApplicationsOffers;
  'app.careerApplicationStages': AppCareerApplicationStages;
  'app.careerCertifications': AppCareerCertifications;
  'app.careerEducation': AppCareerEducation;
  'app.careerEngagements': AppCareerEngagements;
  'app.careerImportJobs': AppCareerImportJobs;
  'app.careerProfile': AppCareerProfile;
  'app.careerProjectEngagements': AppCareerProjectEngagements;
  'app.careerProjects': AppCareerProjects;
  'app.careerSkills': AppCareerSkills;
  'app.careerSocialLinks': AppCareerSocialLinks;
  'app.careerTestimonials': AppCareerTestimonials;
  'app.chatGenerationEvents': AppChatGenerationEvents;
  'app.chatGenerationRuns': AppChatGenerationRuns;
  'app.chatGenerationToolEffects': AppChatGenerationToolEffects;
  'app.chatMessages': AppChatMessages;
  'app.chats': AppChats;
  'app.chatSources': AppChatSources;
  'app.chatSpeechRuns': AppChatSpeechRuns;
  'app.collectionItems': AppCollectionItems;
  'app.collectionMembers': AppCollectionMembers;
  'app.collections': AppCollections;
  'app.files': AppFiles;
  'app.financeAccounts': AppFinanceAccounts;
  'app.financeCategories': AppFinanceCategories;
  'app.financeInstitutions': AppFinanceInstitutions;
  'app.financeTransactions': AppFinanceTransactions;
  'app.healthActivities': AppHealthActivities;
  'app.healthObservations': AppHealthObservations;
  'app.healthProfiles': AppHealthProfiles;
  'app.healthSupplements': AppHealthSupplements;
  'app.mediaCollectionItems': AppMediaCollectionItems;
  'app.mediaCollections': AppMediaCollections;
  'app.mediaItemActivities': AppMediaItemActivities;
  'app.mediaItemIdentifiers': AppMediaItemIdentifiers;
  'app.mediaItems': AppMediaItems;
  'app.musicAlbums': AppMusicAlbums;
  'app.noteFiles': AppNoteFiles;
  'app.notes': AppNotes;
  'app.organizationMemberships': AppOrganizationMemberships;
  'app.organizations': AppOrganizations;
  'app.people': AppPeople;
  'app.personAddressRentHistory': AppPersonAddressRentHistory;
  'app.personArtists': AppPersonArtists;
  'app.personContactMethods': AppPersonContactMethods;
  'app.personRelationships': AppPersonRelationships;
  'app.personServices': AppPersonServices;
  'app.places': AppPlaces;
  'app.placeVisits': AppPlaceVisits;
  'app.plaidItems': AppPlaidItems;
  'app.possessionImages': AppPossessionImages;
  'app.possessions': AppPossessions;
  'app.socialContacts': AppSocialContacts;
  'app.socialEngagements': AppSocialEngagements;
  'app.socialMessages': AppSocialMessages;
  'app.socialPosts': AppSocialPosts;
  'app.socialThreadParticipants': AppSocialThreadParticipants;
  'app.socialThreads': AppSocialThreads;
  'app.tagAssignments': AppTagAssignments;
  'app.tags': AppTags;
  'app.taskParticipants': AppTaskParticipants;
  'app.tasks': AppTasks;
  'app.travelSegments': AppTravelSegments;
  'app.travelTripAttendees': AppTravelTripAttendees;
  'app.travelTrips': AppTravelTrips;
  'app.vectorDocuments': AppVectorDocuments;
  deviceCode: DeviceCode;
  gooseDbVersion: GooseDbVersion;
  jwks: Jwks;
  oauthAccessToken: OauthAccessToken;
  oauthAccessTokenLegacy20260817: OauthAccessTokenLegacy20260817;
  oauthApplicationLegacy20260817: OauthApplicationLegacy20260817;
  oauthClient: OauthClient;
  oauthClientAssertion: OauthClientAssertion;
  oauthClientResource: OauthClientResource;
  oauthConsent: OauthConsent;
  oauthConsentLegacy20260817: OauthConsentLegacy20260817;
  oauthRefreshToken: OauthRefreshToken;
  oauthResource: OauthResource;
  passkey: Passkey;
  rateLimit: RateLimit;
  session: Session;
  user: User;
  verification: Verification;
}
