/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AppAiUsageEvents {
  cachedInputTokens: number | null;
  costUsd: Numeric | null;
  createdat: Generated<Timestamp>;
  feature: string;
  id: Generated<string>;
  inputTokens: number;
  metadata: Json | null;
  model: string;
  operation: string;
  outputTokens: number;
  ownerUserid: string;
  provider: string;
  reasoningTokens: number | null;
  requestId: string | null;
  totalTokens: number;
}

export interface AppApplicationFiles {
  applicationId: string;
  createdat: Generated<Timestamp>;
  fileContent: string | null;
  fileName: string;
  fileSize: number | null;
  fileUrl: string | null;
  id: Generated<string>;
  mimeType: string | null;
  type: string;
  updatedat: Generated<Timestamp>;
}

export interface AppApplicationNotes {
  applicationId: string;
  content: string;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  isPrivate: Generated<boolean>;
  title: string | null;
  type: string;
  updatedat: Generated<Timestamp>;
}

export interface AppBookmarks {
  createdat: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  ownerUserid: string;
  placeId: string | null;
  title: string;
  updatedat: Generated<Timestamp>;
  url: string;
}

export interface AppCareerEvents {
  achievements: Generated<Json>;
  bonusAmount: number | null;
  bonusType: string | null;
  careerGoals: Json | null;
  createdat: Generated<Timestamp>;
  description: string | null;
  equityGranted: number | null;
  equityVesting: string | null;
  eventDate: Timestamp;
  eventType: string;
  id: Generated<string>;
  increasePercentage: string | null;
  managerFeedback: string | null;
  marketSalaryRange: Json | null;
  newLevel: string | null;
  newSalary: number | null;
  newTitle: string | null;
  newTotalComp: number | null;
  ownerUserid: string;
  performanceRating: string | null;
  previousLevel: string | null;
  previousSalary: number | null;
  previousTitle: string | null;
  previousTotalComp: number | null;
  salaryIncrease: number | null;
  selfAssessment: string | null;
  skillsGained: Generated<Json>;
  totalCompIncrease: number | null;
  updatedat: Generated<Timestamp>;
  workExperienceId: string | null;
}

export interface AppCertifications {
  category: string | null;
  cost: number | null;
  createdat: Generated<Timestamp>;
  description: string | null;
  expirationDate: Timestamp | null;
  id: Generated<string>;
  issueDate: Timestamp;
  issuingOrganization: string;
  isVisible: Generated<boolean>;
  name: string;
  nextRenewalDate: Timestamp | null;
  ownerUserid: string;
  sortOrder: Generated<number>;
  status: Generated<string>;
  updatedat: Generated<Timestamp>;
  workExperienceId: string | null;
}

export interface AppChatMessages {
  authorUserid: string | null;
  chatId: string;
  content: string;
  createdat: Generated<Timestamp>;
  files: Json | null;
  id: Generated<string>;
  parentMessageId: string | null;
  reasoning: string | null;
  referencedNoteIds: Json | null;
  role: string;
  toolCalls: Json | null;
  updatedat: Generated<Timestamp>;
}

export interface AppChats {
  archivedAt: Timestamp | null;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  lastMessageAt: Generated<Timestamp>;
  noteId: string | null;
  ownerUserid: string;
  primarySpaceId: string | null;
  source: string | null;
  title: string;
  updatedat: Generated<Timestamp>;
}

export interface AppCompanies {
  createdat: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  industry: string | null;
  location: string | null;
  name: string;
  ownerUserid: string;
  size: number | null;
  updatedat: Generated<Timestamp>;
  website: string | null;
}

export interface AppEntities {
  createdat: Generated<Timestamp>;
  entityId: string;
  entityTable: string;
  ownerUserid: string | null;
  primarySpaceId: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppEntityLinks {
  createdat: Generated<Timestamp>;
  fromEntityId: string;
  fromEntityTable: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  ownerUserid: string;
  relationType: string;
  spaceId: string | null;
  toEntityId: string;
  toEntityTable: string;
  updatedat: Generated<Timestamp>;
  validDuring: Generated<string>;
}

export interface AppEventAttendees {
  createdat: Generated<Timestamp>;
  email: string | null;
  eventId: string;
  id: Generated<string>;
  personId: string | null;
  respondedAt: Timestamp | null;
  role: Generated<string>;
  status: Generated<string>;
  updatedat: Generated<Timestamp>;
}

export interface AppEvents {
  color: string | null;
  createdat: Generated<Timestamp>;
  description: string | null;
  endsAt: Timestamp | null;
  eventType: string;
  externalId: string | null;
  id: Generated<string>;
  isAllDay: Generated<boolean>;
  metadata: Generated<Json>;
  ownerUserid: string;
  placeId: string | null;
  recurrence: Generated<Json>;
  source: string | null;
  startsAt: Timestamp;
  title: string;
  updatedat: Generated<Timestamp>;
}

export interface AppFiles {
  content: string | null;
  createdat: Generated<Timestamp>;
  id: string;
  metadata: Json | null;
  mimetype: string;
  originalName: string;
  ownerUserid: string;
  size: number;
  storageKey: string;
  textContent: string | null;
  updatedat: Generated<Timestamp>;
  url: string;
}

export interface AppFinanceAccounts {
  accountid: string | null;
  accountSubtype: string | null;
  accountType: string;
  availableBalance: Numeric | null;
  createdat: Generated<Timestamp>;
  currencyCode: Generated<string>;
  currentBalance: Numeric | null;
  id: Generated<string>;
  institutionId: string | null;
  isActive: Generated<boolean>;
  mask: string | null;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  plaidItemId: string | null;
  provider: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppFinanceInstitutions {
  countryCode: string | null;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  logoUrl: string | null;
  name: string;
  provider: string | null;
  providerInstitutionId: string | null;
  updatedat: Generated<Timestamp>;
  websiteUrl: string | null;
}

export interface AppFinanceTransactions {
  accountId: string;
  amount: Numeric;
  createdat: Generated<Timestamp>;
  description: string | null;
  externalId: string | null;
  id: Generated<string>;
  merchantName: string | null;
  notes: string | null;
  occurredAt: Timestamp | null;
  ownerUserid: string;
  pending: Generated<boolean>;
  postedOn: Timestamp;
  providerPayload: Generated<Json>;
  source: string | null;
  transactionType: string;
  updatedat: Generated<Timestamp>;
}

export interface AppGoals {
  createdat: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  ownerUserid: string;
  status: Generated<string>;
  targetAt: Timestamp | null;
  title: string;
  updatedat: Generated<Timestamp>;
}

export interface AppJobApplications {
  applicationDate: Timestamp | null;
  bonusFinal: number | null;
  bonusOffered: number | null;
  companyId: string;
  companyNotes: string | null;
  coverLetter: string | null;
  createdat: Generated<Timestamp>;
  decisionDate: Timestamp | null;
  endDate: Timestamp | null;
  equityFinal: string | null;
  equityOffered: string | null;
  firstInterviewDate: Timestamp | null;
  id: Generated<string>;
  interviewDates: Generated<Json>;
  jobId: string | null;
  jobPosting: string | null;
  jobPostingUrl: string | null;
  jobPostingWordCount: number | null;
  link: string | null;
  location: string | null;
  negotiationNotes: string | null;
  offerDate: Timestamp | null;
  ownerUserid: string;
  phoneScreen: string | null;
  position: string;
  recruiterEmail: string | null;
  recruiterLinkedin: string | null;
  recruiterName: string | null;
  reference: Generated<boolean>;
  rejectionReason: string | null;
  requirements: Generated<Json>;
  responseDate: Timestamp | null;
  resume: string | null;
  salaryAccepted: string | null;
  salaryExpected: number | null;
  salaryFinal: number | null;
  salaryNegotiated: number | null;
  salaryOffered: number | null;
  salaryQuoted: string | null;
  salaryRequested: number | null;
  skills: Generated<Json>;
  source: string | null;
  stages: Generated<Json>;
  startDate: Timestamp;
  status: string;
  timeToDecision: number | null;
  timeToFirstInterview: number | null;
  timeToOffer: number | null;
  timeToResponse: number | null;
  totalCompFinal: number | null;
  totalCompOffered: number | null;
  updatedat: Generated<Timestamp>;
  withdrawalReason: string | null;
}

export interface AppKeyResults {
  createdat: Generated<Timestamp>;
  currentValue: Numeric | null;
  dueAt: Timestamp | null;
  goalId: string;
  id: Generated<string>;
  targetValue: Numeric | null;
  title: string;
  unit: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppMusicAlbums {
  albumArtUrl: string | null;
  artistId: string | null;
  artistName: string | null;
  createdat: Generated<Timestamp>;
  externalId: string | null;
  genre: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  ownerUserid: string;
  releaseDate: Timestamp | null;
  source: string;
  title: string;
  updatedat: Generated<Timestamp>;
}

export interface AppMusicArtists {
  createdat: Generated<Timestamp>;
  externalId: string | null;
  genre: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  source: string;
  updatedat: Generated<Timestamp>;
}

export interface AppMusicListens {
  completed: Generated<boolean>;
  contextId: string | null;
  contextType: string | null;
  createdat: Generated<Timestamp>;
  durationSeconds: number | null;
  endedAt: Timestamp | null;
  id: Generated<string>;
  ownerUserid: string;
  source: string;
  startedAt: Timestamp;
  trackId: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppMusicPlaylists {
  createdat: Generated<Timestamp>;
  description: string | null;
  externalId: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  isPublic: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  source: string;
  updatedat: Generated<Timestamp>;
}

export interface AppMusicPlaylistTracks {
  addedAt: Generated<Timestamp>;
  playlistId: string;
  position: number;
  trackId: string;
}

export interface AppMusicTracks {
  albumArtUrl: string | null;
  albumId: string | null;
  albumName: string | null;
  artistId: string | null;
  artistName: string | null;
  createdat: Generated<Timestamp>;
  discNumber: number | null;
  durationSeconds: number | null;
  externalId: string | null;
  genre: string | null;
  id: Generated<string>;
  isrc: string | null;
  metadata: Generated<Json>;
  ownerUserid: string;
  source: string;
  title: string;
  trackNumber: number | null;
  updatedat: Generated<Timestamp>;
}

export interface AppNoteFiles {
  attachedAt: Generated<Timestamp>;
  fileId: string;
  noteId: string;
}

export interface AppNotes {
  archivedAt: Timestamp | null;
  content: Generated<string>;
  createdat: Generated<Timestamp>;
  currentVersionId: string | null;
  excerpt: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  ownerUserid: string;
  parentNoteId: string | null;
  source: string | null;
  title: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppNoteShares {
  accessPeriod: Generated<string | null>;
  createdat: Generated<Timestamp>;
  expiresat: Timestamp | null;
  grantedByUserid: string | null;
  id: Generated<string>;
  noteId: string;
  permission: Generated<string>;
  revokedat: Timestamp | null;
  sharedWithUserid: string;
}

export interface AppNoteVersions {
  analysis: Json | null;
  content: string | null;
  createdat: Generated<Timestamp>;
  createdByUserid: string | null;
  excerpt: string | null;
  id: Generated<string>;
  mentions: Generated<Json>;
  noteId: string;
  noteType: Generated<string>;
  publishedAt: Timestamp | null;
  publishingMetadata: Json | null;
  scheduledFor: Timestamp | null;
  status: Generated<string>;
  title: string | null;
  updatedat: Generated<Timestamp>;
  versionNumber: number;
}

export interface AppPeople {
  createdat: Generated<Timestamp>;
  email: string | null;
  endedAt: Timestamp | null;
  firstName: string | null;
  id: Generated<string>;
  image: string | null;
  lastName: string | null;
  metadata: Generated<Json>;
  notes: string | null;
  ownerUserid: string;
  personType: Generated<string>;
  phone: string | null;
  startedAt: Timestamp | null;
  updatedat: Generated<Timestamp>;
}

export interface AppPlaces {
  address: string | null;
  createdat: Generated<Timestamp>;
  externalId: string | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string;
  notes: string | null;
  ownerUserid: string;
  placeType: string | null;
  providerPayload: Generated<Json>;
  rating: Numeric | null;
  source: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppPlaidItems {
  accesstoken: string | null;
  createdat: Generated<Timestamp>;
  cursor: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  institutionId: string | null;
  lastSyncedAt: Timestamp | null;
  ownerUserid: string;
  provider: Generated<string>;
  providerItemId: string;
  status: Generated<string>;
  updatedat: Generated<Timestamp>;
}

export interface AppPortfolioAnalytics {
  city: string | null;
  country: string | null;
  createdat: Generated<Timestamp>;
  event: string;
  id: Generated<string>;
  ipAddress: string | null;
  metadata: Json | null;
  path: string | null;
  portfolioId: string;
  referer: string | null;
  userAgent: string | null;
  visitorId: string | null;
}

export interface AppPortfolios {
  availabilityMessage: string | null;
  availabilityStatus: Generated<boolean>;
  bio: string;
  copyright: string | null;
  createdat: Generated<Timestamp>;
  currentLocation: string;
  email: string;
  id: Generated<string>;
  initials: string | null;
  isActive: Generated<boolean>;
  isPublic: Generated<boolean>;
  jobTitle: string;
  locationTagline: string | null;
  name: string;
  ownerUserid: string;
  phone: string | null;
  profileImageUrl: string | null;
  slug: string;
  tagline: string;
  theme: Json | null;
  title: string;
  updatedat: Generated<Timestamp>;
}

export interface AppPossessionContainers {
  createdat: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  location: string | null;
  name: string;
  ownerUserid: string;
  updatedat: Generated<Timestamp>;
}

export interface AppPossessionEvents {
  amount: Numeric | null;
  amountUnit: string | null;
  containerId: string | null;
  createdat: Generated<Timestamp>;
  endDate: Timestamp | null;
  eventType: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  method: string | null;
  occurredAt: Timestamp | null;
  ownerUserid: string;
  possessionid: string;
  startDate: Timestamp | null;
  updatedat: Generated<Timestamp>;
}

export interface AppPossessions {
  containerId: string | null;
  createdat: Generated<Timestamp>;
  currentValue: Numeric | null;
  description: string | null;
  id: Generated<string>;
  itemCondition: string | null;
  location: string | null;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  purchaseDate: Timestamp | null;
  purchasePrice: Numeric | null;
  serialNumber: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppProjects {
  createdat: Generated<Timestamp>;
  description: string;
  endDate: Timestamp | null;
  githubUrl: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  isFeatured: Generated<boolean>;
  isVisible: Generated<boolean>;
  liveUrl: string | null;
  portfolioId: string;
  shortDescription: string | null;
  sortOrder: Generated<number>;
  startDate: Timestamp | null;
  status: Generated<string>;
  technologies: Generated<Json>;
  title: string;
  updatedat: Generated<Timestamp>;
  videoUrl: string | null;
  workExperienceId: string | null;
}

export interface AppSkills {
  aiDerived: Generated<boolean>;
  category: string | null;
  createdat: Generated<Timestamp>;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  isVisible: Generated<boolean>;
  level: number;
  name: string;
  portfolioId: string;
  proof: string | null;
  sortOrder: Generated<number>;
  updatedat: Generated<Timestamp>;
  yearsOfExperience: number | null;
}

export interface AppSocialLinks {
  createdat: Generated<Timestamp>;
  github: string | null;
  id: Generated<string>;
  linkedin: string | null;
  portfolioId: string;
  twitter: string | null;
  updatedat: Generated<Timestamp>;
  website: string | null;
}

export interface AppSpaceInvites {
  acceptedAt: Timestamp | null;
  createdat: Generated<Timestamp>;
  expiresat: Generated<Timestamp>;
  id: Generated<string>;
  invitedUserEmail: string;
  invitedUserEmailNormalized: Generated<string | null>;
  invitedUserid: string | null;
  inviterUserid: string;
  inviteToken: string;
  inviteWindow: Generated<string | null>;
  revokedat: Timestamp | null;
  spaceId: string;
  status: Generated<string>;
  updatedat: Generated<Timestamp>;
}

export interface AppSpaceItems {
  addedAt: Generated<Timestamp>;
  addedByUserid: string | null;
  entityId: string;
  entityTable: string;
  id: Generated<string>;
  isPinned: Generated<boolean>;
  membershipPeriod: Generated<string | null>;
  metadata: Generated<Json>;
  position: Numeric | null;
  removedAt: Timestamp | null;
  spaceId: string;
}

export interface AppSpaceMembers {
  addedByUserid: string | null;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  membershipPeriod: Generated<string>;
  spaceId: string;
  userid: string;
}

export interface AppSpaces {
  color: string | null;
  createdat: Generated<Timestamp>;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  isOrdered: Generated<boolean>;
  name: string;
  ownerUserid: string;
  updatedat: Generated<Timestamp>;
}

export interface AppSpaceTags {
  createdat: Generated<Timestamp>;
  createdByUserid: string | null;
  id: Generated<string>;
  spaceId: string;
  tagId: string;
}

export interface AppTagAliases {
  alias: string;
  aliasSlug: string;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  tagId: string;
}

export interface AppTagAssignments {
  assignedByUserid: string | null;
  assignmentPeriod: Generated<string | null>;
  assignmentSource: Generated<string>;
  confidence: Numeric | null;
  createdat: Generated<Timestamp>;
  entityId: string;
  entityTable: string;
  id: Generated<string>;
  removedAt: Timestamp | null;
  tagId: string;
}

export interface AppTags {
  archivedAt: Timestamp | null;
  color: string | null;
  createdat: Generated<Timestamp>;
  createdByUserid: string | null;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  name: string;
  ownerUserid: string;
  path: string;
  slug: string;
  updatedat: Generated<Timestamp>;
}

export interface AppTaskAssignments {
  assignedByUserid: string | null;
  assigneeUserid: string;
  assignmentPeriod: Generated<string>;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  primarySpaceId: string;
  taskId: string;
}

export interface AppTasks {
  completedAt: Timestamp | null;
  createdat: Generated<Timestamp>;
  description: string | null;
  dueAt: Timestamp | null;
  id: Generated<string>;
  ownerUserid: string;
  parentTaskId: string | null;
  primarySpaceId: string | null;
  priority: Generated<string>;
  status: Generated<string>;
  title: string;
  updatedat: Generated<Timestamp>;
}

export interface AppTestimonials {
  avatarUrl: string | null;
  company: string | null;
  content: string;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  isVerified: Generated<boolean>;
  isVisible: Generated<boolean>;
  linkedinUrl: string | null;
  name: string;
  portfolioId: string;
  rating: number | null;
  sortOrder: Generated<number>;
  title: string | null;
  updatedat: Generated<Timestamp>;
}

export interface AppTravelTrips {
  createdat: Generated<Timestamp>;
  description: string | null;
  endDate: Timestamp | null;
  id: Generated<string>;
  name: string;
  notes: string | null;
  ownerUserid: string;
  startDate: Timestamp;
  status: Generated<string>;
  updatedat: Generated<Timestamp>;
}

export interface AppUserPortfolioPreferences {
  createdat: Generated<Timestamp>;
  currentPortfolioId: string | null;
  updatedat: Generated<Timestamp>;
  userId: string;
}

export interface AppVectorDocuments {
  content: string;
  createdat: Generated<Timestamp>;
  embedding: string;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  metadata: Json | null;
  ownerUserid: string;
  updatedat: Generated<Timestamp>;
}

export interface AppVideoChannels {
  createdat: Generated<Timestamp>;
  description: string | null;
  externalId: string | null;
  handle: string | null;
  id: Generated<string>;
  image: string | null;
  metadata: Generated<Json>;
  name: string;
  ownerUserid: string;
  source: string;
  subscriberCount: number | null;
  updatedat: Generated<Timestamp>;
}

export interface AppVideoViews {
  channelId: string | null;
  channelName: string | null;
  completed: Generated<boolean>;
  contentType: string;
  createdat: Generated<Timestamp>;
  description: string | null;
  durationSeconds: number | null;
  episodeNumber: number | null;
  externalId: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  ownerUserid: string;
  seasonNumber: number | null;
  source: string;
  thumbnailUrl: string | null;
  title: string;
  updatedat: Generated<Timestamp>;
  watchedAt: Timestamp;
  watchTimeSeconds: Generated<number>;
}

export interface AppWorkExperiences {
  action: string | null;
  annualBonus: number | null;
  baseSalary: number | null;
  benefits: Json | null;
  bonusHistory: Generated<Json>;
  company: string;
  createdat: Generated<Timestamp>;
  currency: Generated<string>;
  department: string | null;
  description: string;
  directReports: Generated<number>;
  employmentType: Generated<string>;
  endDate: Timestamp | null;
  exitNotes: string | null;
  gradient: string | null;
  id: Generated<string>;
  image: string | null;
  isVisible: Generated<boolean>;
  metadata: Json | null;
  metrics: string | null;
  performanceRatings: Generated<Json>;
  portfolioId: string;
  reasonForLeaving: string | null;
  reportsTo: string | null;
  role: string;
  salaryAdjustments: Generated<Json>;
  salaryRange: Json | null;
  seniorityLevel: string | null;
  signingBonus: number | null;
  sortOrder: Generated<number>;
  startDate: Timestamp | null;
  tags: Generated<Json>;
  teamSize: number | null;
  updatedat: Generated<Timestamp>;
  workArrangement: Generated<string>;
}

export interface DeviceCode {
  clientId: string | null;
  deviceCode: string;
  expiresAt: Timestamp;
  id: string;
  lastPolledAt: Timestamp | null;
  pollingInterval: number | null;
  scope: string | null;
  status: string;
  userCode: string;
  userId: string | null;
}

export interface GooseDbVersion {
  id: Generated<number>;
  isApplied: boolean;
  tstamp: Generated<Timestamp>;
  versionId: Int8;
}

export interface Jwks {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface LabsCaseUpdates {
  caseId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  neutralContent: string;
  rawContent: string;
  round: number;
}

export interface LabsCovidData {
  aged65Older: number | null;
  aged70Older: number | null;
  cardiovascDeathRate: number | null;
  continent: string | null;
  date: Timestamp | null;
  diabetesPrevalence: number | null;
  excessMortality: number | null;
  excessMortalityCumulative: number | null;
  excessMortalityCumulativeAbsolute: number | null;
  excessMortalityCumulativePerMillion: number | null;
  extremePoverty: number | null;
  femaleSmokers: number | null;
  gdpPerCapita: number | null;
  handwashingFacilities: number | null;
  hospitalBedsPerThousand: number | null;
  hospPatients: number | null;
  hospPatientsPerMillion: number | null;
  humanDevelopmentIndex: number | null;
  icuPatients: number | null;
  icuPatientsPerMillion: number | null;
  id: Generated<number>;
  isoCode: string | null;
  lifeExpectancy: number | null;
  location: string | null;
  maleSmokers: number | null;
  medianAge: number | null;
  newCases: number | null;
  newCasesPerMillion: number | null;
  newCasesSmoothed: number | null;
  newCasesSmoothedPerMillion: number | null;
  newDeaths: number | null;
  newDeathsPerMillion: number | null;
  newDeathsSmoothed: number | null;
  newDeathsSmoothedPerMillion: number | null;
  newPeopleVaccinatedSmoothed: number | null;
  newPeopleVaccinatedSmoothedPerHundred: number | null;
  newTests: number | null;
  newTestsPerThousand: number | null;
  newTestsSmoothed: number | null;
  newTestsSmoothedPerThousand: number | null;
  newVaccinations: number | null;
  newVaccinationsSmoothed: number | null;
  newVaccinationsSmoothedPerMillion: number | null;
  peopleFullyVaccinated: Int8 | null;
  peopleFullyVaccinatedPerHundred: number | null;
  peopleVaccinated: Int8 | null;
  peopleVaccinatedPerHundred: number | null;
  population: Int8 | null;
  populationDensity: number | null;
  positiveRate: number | null;
  reproductionRate: number | null;
  stringencyIndex: number | null;
  testsPerCase: number | null;
  testsUnits: string | null;
  totalBoosters: Int8 | null;
  totalBoostersPerHundred: number | null;
  totalCases: number | null;
  totalCasesPerMillion: number | null;
  totalDeaths: number | null;
  totalDeathsPerMillion: number | null;
  totalTests: number | null;
  totalTestsPerThousand: number | null;
  totalVaccinations: Int8 | null;
  totalVaccinationsPerHundred: number | null;
  weeklyHospAdmissions: number | null;
  weeklyHospAdmissionsPerMillion: number | null;
  weeklyIcuAdmissions: number | null;
  weeklyIcuAdmissionsPerMillion: number | null;
}

export interface LabsDrizzleMigrations {
  createdAt: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface LabsRelationshipCases {
  createdAt: Generated<Timestamp>;
  id: string;
  label: string | null;
  neutralSituation: string;
  question: string;
  quorumSize: Generated<number>;
  rawSituation: string;
  status: Generated<string>;
  userId: string | null;
}

export interface LabsRelationshipVerdicts {
  caseId: string;
  comment: string;
  createdAt: Generated<Timestamp>;
  fingerprint: string;
  id: string;
  updateId: string | null;
  updateRound: Generated<number>;
  userId: string | null;
  value: string;
}

export interface LabsRhobhDailyPuzzles {
  answer: string;
  answerType: string;
  clue: string;
  createdAt: Generated<Timestamp>;
  dateUtc: Timestamp | null;
  detail: string;
  id: Generated<number>;
  normalizedAnswer: string;
  sources: Generated<Json>;
  updatedAt: Generated<Timestamp>;
}

export interface LabsSearchDocuments {
  body: string;
  category: string;
  createdAt: Generated<Timestamp>;
  embedding: string;
  featured: Generated<boolean>;
  id: Generated<number>;
  kind: string;
  location: string;
  popularity: Generated<number>;
  publishedAt: Timestamp;
  searchText: string;
  searchVector: Generated<string>;
  sourceUrl: string;
  subtitle: string;
  summary: string;
  tags: Json;
  title: string;
  updatedAt: Generated<Timestamp>;
  year: number;
}

export interface LabsTflCameras {
  available: boolean | null;
  commonName: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  imageUrl: string | null;
  lat: number;
  lng: number;
  tflId: string;
  updatedAt: Generated<Timestamp>;
  videoUrl: string | null;
  view: string | null;
}

export interface OpsAuditLogs {
  action: string;
  actorUserid: string | null;
  createdat: Generated<Timestamp>;
  entityId: string | null;
  entitySchema: string | null;
  entityTable: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
}

export interface OpsSearchLogs {
  actorUserid: string | null;
  clickedEntityId: string | null;
  clickedEntityType: string | null;
  createdat: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  query: string;
  resultsCount: number | null;
  scope: string | null;
}

export interface Passkey {
  aaguid: string | null;
  backedUp: Generated<boolean>;
  counter: Generated<number>;
  createdAt: Timestamp | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

// --- Finance tables (public schema, from 20260705000000 migration) ---

export interface FinanceAccounts {
  id: string;
  user_id: string;
  name: string;
  account_type: string;
  balance: number;
  data: Json | null;
  institution_id?: string | null;
  plaid_item_id?: string | null;
  created_at?: Timestamp | null;
  updated_at?: Timestamp | null;
}

export interface FinanceTransactions {
  id: string;
  user_id: string;
  account_id: string;
  amount: number;
  description: string | null;
  date?: Timestamp | string | null;
  posted_on?: Timestamp | string | null;
  occurred_at?: Timestamp | string | null;
  external_id?: string | null;
  category?: string | null;
  merchant_name?: string | null;
  notes?: string | null;
  transaction_type?: string | null;
  pending?: boolean;
  source?: string | null;
  created_at?: Timestamp | null;
  updated_at?: Timestamp | null;
}

export interface PlaidItems {
  id: string;
  user_id: string;
  item_id: string;
  institution_id: string | null;
  cursor: string | null;
  access_token: string | null;
  status: string | null;
  last_synced_at: Timestamp | string | null;
  error_code?: string | null;
  error_message?: string | null;
  error?: string | null;
  created_at?: Timestamp | null;
  updated_at?: Timestamp | null;
}

export interface Tags {
  id: string;
  owner_id: string;
  name: string;
  color: string | null;
  description?: string | null;
  icon?: string | null;
  path?: string;
  slug?: string;
}

export interface TaggedItems {
  id: string;
  tag_id: string;
  entity_id: string;
  entity_type: string;
  assigned_by_userid?: string | null;
  assignment_source?: string;
  assignment_period?: string | null;
  confidence?: number | null;
  removed_at?: Timestamp | string | null;
}

export interface BudgetGoals {
  id: string;
  user_id: string;
  category_id: string | null;
  target_amount: number;
  target_period: string;
  created_at?: Timestamp | null;
}

export interface FinancialInstitutions {
  id: string;
  name: string;
  logo_url?: string | null;
  website_url?: string | null;
  provider?: string | null;
  provider_institution_id?: string | null;
  country_code?: string | null;
}

export interface DB {
  account: Account;
  'app.aiUsageEvents': AppAiUsageEvents;
  'app.applicationFiles': AppApplicationFiles;
  'app.applicationNotes': AppApplicationNotes;
  'app.bookmarks': AppBookmarks;
  'app.careerEvents': AppCareerEvents;
  'app.certifications': AppCertifications;
  'app.chatMessages': AppChatMessages;
  'app.chats': AppChats;
  'app.companies': AppCompanies;
  'app.entities': AppEntities;
  'app.entityLinks': AppEntityLinks;
  'app.eventAttendees': AppEventAttendees;
  'app.events': AppEvents;
  'app.files': AppFiles;
  'app.financeAccounts': AppFinanceAccounts;
  'app.financeInstitutions': AppFinanceInstitutions;
  'app.financeTransactions': AppFinanceTransactions;
  'app.goals': AppGoals;
  'app.jobApplications': AppJobApplications;
  'app.keyResults': AppKeyResults;
  'app.musicAlbums': AppMusicAlbums;
  'app.musicArtists': AppMusicArtists;
  'app.musicListens': AppMusicListens;
  'app.musicPlaylists': AppMusicPlaylists;
  'app.musicPlaylistTracks': AppMusicPlaylistTracks;
  'app.musicTracks': AppMusicTracks;
  'app.noteFiles': AppNoteFiles;
  'app.notes': AppNotes;
  'app.noteShares': AppNoteShares;
  'app.noteVersions': AppNoteVersions;
  'app.people': AppPeople;
  'app.places': AppPlaces;
  'app.plaidItems': AppPlaidItems;
  'app.portfolioAnalytics': AppPortfolioAnalytics;
  'app.portfolios': AppPortfolios;
  'app.possessionContainers': AppPossessionContainers;
  'app.possessionEvents': AppPossessionEvents;
  'app.possessions': AppPossessions;
  'app.projects': AppProjects;
  'app.skills': AppSkills;
  'app.socialLinks': AppSocialLinks;
  'app.spaceInvites': AppSpaceInvites;
  'app.spaceItems': AppSpaceItems;
  'app.spaceMembers': AppSpaceMembers;
  'app.spaces': AppSpaces;
  'app.spaceTags': AppSpaceTags;
  'app.tagAliases': AppTagAliases;
  'app.tagAssignments': AppTagAssignments;
  'app.tags': AppTags;
  tagged_items: TaggedItems;
  tags: Tags;
  'app.taskAssignments': AppTaskAssignments;
  'app.tasks': AppTasks;
  'app.testimonials': AppTestimonials;
  'app.travelTrips': AppTravelTrips;
  'app.userPortfolioPreferences': AppUserPortfolioPreferences;
  'app.vectorDocuments': AppVectorDocuments;
  'app.videoChannels': AppVideoChannels;
  'app.videoViews': AppVideoViews;
  'app.workExperiences': AppWorkExperiences;
  budget_goals: BudgetGoals;
  deviceCode: DeviceCode;
  finance_accounts: FinanceAccounts;
  finance_transactions: FinanceTransactions;
  financial_institutions: FinancialInstitutions;
  gooseDbVersion: GooseDbVersion;
  jwks: Jwks;
  'labs.caseUpdates': LabsCaseUpdates;
  'labs.covidData': LabsCovidData;
  'labs.DrizzleMigrations': LabsDrizzleMigrations;
  'labs.relationshipCases': LabsRelationshipCases;
  'labs.relationshipVerdicts': LabsRelationshipVerdicts;
  'labs.rhobhDailyPuzzles': LabsRhobhDailyPuzzles;
  'labs.searchDocuments': LabsSearchDocuments;
  'labs.tflCameras': LabsTflCameras;
  'ops.auditLogs': OpsAuditLogs;
  'ops.searchLogs': OpsSearchLogs;
  passkey: Passkey;
  plaid_items: PlaidItems;
  session: Session;
  user: User;
  verification: Verification;
}
