import { type RouteConfig, index, layout, prefix, route } from '@react-router/dev/routes'

export default [
  index('routes/home.tsx'),
  route('/login', 'routes/login.tsx'),
  route('/account', 'routes/account.tsx'),
  route('/health', 'routes/health.ts'),
  route('/api/applications/create', 'routes/api.applications.create.ts'),
  route('/api/job/scrape', 'routes/api.job.scrape.ts'),
  route('/api/portfolio/:userId', 'routes/api.portfolio.$userId.ts'),
  route('/api/resume/convert', 'routes/api.resume.convert.ts'),
  route('/api/validate-slug', 'routes/api.validate-slug.ts'),
  route('/auth/callback', 'routes/auth.callback.ts'),
  ...prefix('/career', [
    index('routes/career.tsx'),
    route('/applications', 'routes/career.applications.tsx'),
    route('/experience/:id', 'routes/career.experience.$id.tsx'),
    route('/experience/:id/projects', 'routes/career.experience.$id.projects.tsx'),
    route('/applications/create', 'routes/career.applications.create.tsx'),
    route('/applications/:id', 'routes/career.applications.$id.tsx'),
    route('/certifications', 'routes/career.certifications.tsx'),
  ]),
  route('/projects', 'routes/career.projects.tsx'),
  route('/onboarding', 'routes/onboarding.tsx'),
  route('/onboarding/complete', 'routes/onboarding.complete.tsx'),
  route('/demo', 'routes/demo.tsx'),
  route('/api/resume/customize', 'routes/api.resume.customize.ts'),
  route('/resume/custom', 'routes/resume.custom.tsx'),
  route('/p/:slug', 'routes/p.$slug.tsx'),
  layout('routes/editor.tsx', [
    route('/editor', 'routes/editor.basic.tsx'),
    route('/editor/work', 'routes/editor.work.tsx'),
    route('/editor/skills', 'routes/editor.skills.tsx'),
    route('/editor/social', 'routes/editor.social.tsx'),
    route('/editor/stats', 'routes/editor.stats.tsx'),
    route('/editor/projects', 'routes/editor.projects.tsx'),
    route('/editor/testimonials', 'routes/editor.testimonials.tsx'),
  ]),
] satisfies RouteConfig
