import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
  route('/login', 'routes/login.tsx'),
  route('/account', 'routes/account.tsx'),
  route('/health', 'routes/health.ts'),
  route('/api/applications/create', 'routes/api.applications.create.ts'),
  route('/api/job/scrape', 'routes/api.job.scrape.ts'),
  route('/api/portfolio/:owner_userid', 'routes/api.portfolio.$userId.ts'),
  route('/api/resume/convert', 'routes/api.resume.convert.ts'),
  route('/api/validate-slug', 'routes/api.validate-slug.ts'),
  route('/api/resume/customize', 'routes/api.resume.customize.ts'),
  route('/onboarding', 'routes/onboarding.tsx'),
  route('/demo', 'routes/demo.tsx'),
  route('/resume/custom', 'routes/resume.custom.tsx'),
  route('/p/:slug', 'routes/p.$slug.tsx'),
  route('/work', 'routes/work.tsx'),
  route('/work/:id', 'routes/work.$id.tsx'),
  route('/work/:id/projects', 'routes/work.$id.projects.tsx'),
  route('/skills', 'routes/skills.tsx'),
  route('/social', 'routes/social.tsx'),
  route('/stats', 'routes/stats.tsx'),
  route('/projects', 'routes/projects.tsx'),
  route('/testimonials', 'routes/testimonials.tsx'),
  route('/applications', 'routes/applications.tsx'),
  route('/applications/new', 'routes/applications.new.tsx'),
  route('/applications/:id', 'routes/applications.$id.tsx'),
  route('/certifications', 'routes/certifications.tsx'),
] satisfies RouteConfig;
