import { pgTable, index, foreignKey, unique, pgPolicy, text, uuid, timestamp, check, integer, varchar, uniqueIndex, jsonb, boolean, numeric, date, bigint, primaryKey, pgView, interval, vector, geometry } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * calendar domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
 *   - users
 *   - persons
 *   - calendarEvents
 *   - calendarAttendees
 */

export const users = pgTable("users", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	name: text(),
	avatarUrl: text("avatar_url"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("users_email_lower_idx").using("btree", sql`lower(email)`),
	unique("users_email_key").on(table.email),
	pgPolicy("users_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (id = app_current_user_id()))`  }),
]);

export const persons = pgTable("persons", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	ownerUserId: uuid("owner_user_id").notNull(),
	personType: text("person_type").notNull(),
	firstName: text("first_name"),
	lastName: text("last_name"),
	email: text(),
	phone: text(),
	avatarUrl: text("avatar_url"),
	notes: text(),
	metadata: jsonb().default({}),
	dateStarted: timestamp("date_started", { withTimezone: true, mode: 'string' }),
	dateEnded: timestamp("date_ended", { withTimezone: true, mode: 'string' }),
	// TODO: failed to parse database type 'tsvector'
	searchVector: text("search_vector").generatedAlwaysAs(sql`to_tsvector('simple'::regconfig, ((((((COALESCE(first_name, ''::text) || ' '::text) || COALESCE(last_name, ''::text)) || ' '::text) || COALESCE(email, ''::text)) || ' '::text) || COALESCE(phone, ''::text)))`),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("persons_email_idx").using("btree", table.ownerUserId.asc().nullsLast().op("uuid_ops"), table.email.asc().nullsLast().op("text_ops")),
	index("persons_name_trgm_idx").using("gin", sql`(((COALESCE(first_name, ''::text) || ' '::text) || COALESCE(las`),
	index("persons_owner_idx").using("btree", table.ownerUserId.asc().nullsLast().op("uuid_ops"), table.personType.asc().nullsLast().op("uuid_ops")),
	index("persons_search_idx").using("gin", table.searchVector.asc().nullsLast().op("tsvector_ops")),
	foreignKey({
			columns: [table.ownerUserId],
			foreignColumns: [users.id],
			name: "persons_owner_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("persons_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (owner_user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (owner_user_id = app_current_user_id()))`  }),
]);

export const calendarEvents = pgTable("calendar_events", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	eventType: text("event_type").notNull(),
	title: text().notNull(),
	description: text(),
	startTime: timestamp("start_time", { withTimezone: true, mode: 'string' }).notNull(),
	endTime: timestamp("end_time", { withTimezone: true, mode: 'string' }),
	allDay: boolean("all_day").default(false),
	location: text(),
	locationCoords: jsonb("location_coords"),
	source: text(),
	externalId: text("external_id"),
	color: text(),
	recurring: jsonb(),
	metadata: jsonb().default({}),
	// TODO: failed to parse database type 'tsvector'
	searchVector: text("search_vector").generatedAlwaysAs(sql`to_tsvector('english'::regconfig, ((((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(location, ''::text)))`),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("calendar_events_agenda_idx").using("btree", table.userId.asc().nullsLast().op("bool_ops"), table.startTime.asc().nullsLast().op("timestamptz_ops"), table.endTime.asc().nullsLast().op("uuid_ops"), table.allDay.asc().nullsLast().op("uuid_ops"), table.title.asc().nullsLast().op("timestamptz_ops"), table.color.asc().nullsLast().op("uuid_ops")),
	index("calendar_events_search_idx").using("gin", table.searchVector.asc().nullsLast().op("tsvector_ops")),
	index("calendar_events_user_time_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.startTime.desc().nullsFirst().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "calendar_events_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("calendar_events_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);

export const calendarAttendees = pgTable("calendar_attendees", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	eventId: uuid("event_id").notNull(),
	personId: uuid("person_id"),
	email: text(),
	status: text().default('needs_action'),
	role: text().default('required'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("calendar_attendees_event_idx").using("btree", table.eventId.asc().nullsLast().op("uuid_ops")),
	index("calendar_attendees_person_idx").using("btree", table.personId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.eventId],
			foreignColumns: [calendarEvents.id],
			name: "calendar_attendees_event_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.personId],
			foreignColumns: [persons.id],
			name: "calendar_attendees_person_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("calendar_attendees_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (EXISTS ( SELECT 1
   FROM calendar_events e
  WHERE ((e.id = calendar_attendees.event_id) AND (e.user_id = app_current_user_id())))))`, withCheck: sql`(app_is_service_role() OR (EXISTS ( SELECT 1
   FROM calendar_events e
  WHERE ((e.id = calendar_attendees.event_id) AND (e.user_id = app_current_user_id())))))`  }),
]);
