import { pgTable, index, foreignKey, unique, pgPolicy, text, uuid, timestamp, check, integer, varchar, uniqueIndex, jsonb, boolean, numeric, date, bigint, primaryKey, pgView, interval, vector, geometry } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * possessions domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
 *   - users
 *   - possessions
 *   - possessionContainers
 */

export const users = pgTable("users", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	name: text(),
	avatarUrl: text("avatar_url"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("users_email_lower_idx").using("btree", sql`lower(email)`),
	unique("users_email_key").on(table.email),
	pgPolicy("users_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (id = app_current_user_id()))`  }),
]);

export const possessions = pgTable("possessions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	containerId: uuid("container_id"),
	name: text().notNull(),
	description: text(),
	category: text(),
	purchaseDate: date("purchase_date"),
	purchasePrice: numeric("purchase_price", { precision: 10, scale:  2 }),
	currentValue: numeric("current_value", { precision: 10, scale:  2 }),
	condition: text(),
	location: text(),
	serialNumber: text("serial_number"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("possessions_category_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.category.asc().nullsLast().op("text_ops")),
	index("possessions_container_idx").using("btree", table.containerId.asc().nullsLast().op("uuid_ops")),
	index("possessions_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.containerId],
			foreignColumns: [possessionContainers.id],
			name: "possessions_container_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "possessions_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("possessions_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);

export const possessionContainers = pgTable("possession_containers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	name: text().notNull(),
	location: text(),
	description: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("possession_containers_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "possession_containers_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("possession_containers_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);
