import { pgTable, index, foreignKey, unique, pgPolicy, text, uuid, timestamp, check, integer, varchar, uniqueIndex, jsonb, boolean, numeric, date, bigint, primaryKey, pgView, interval, vector, geometry } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * tags domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
 *   - users
 *   - tags
 *   - taggedItems
 *   - tagShares
 */

export const users = pgTable("users", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	name: text(),
	avatarUrl: text("avatar_url"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("users_email_lower_idx").using("btree", sql`lower(email)`),
	unique("users_email_key").on(table.email),
	pgPolicy("users_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (id = app_current_user_id()))`  }),
]);

export const tags = pgTable("tags", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	ownerId: uuid("owner_id").notNull(),
	groupId: text("group_id"),
	name: text().notNull(),
	emojiImageUrl: text("emoji_image_url"),
	color: text(),
	description: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("tags_owner_id_idx").using("btree", table.ownerId.asc().nullsLast().op("uuid_ops")),
	uniqueIndex("tags_owner_name_idx").using("btree", table.ownerId.asc().nullsLast().op("text_ops"), table.name.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.ownerId],
			foreignColumns: [users.id],
			name: "tags_owner_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("tags_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (owner_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (owner_id = app_current_user_id()))`  }),
]);

export const taggedItems = pgTable("tagged_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tagId: uuid("tag_id").notNull(),
	entityType: text("entity_type").notNull(),
	entityId: uuid("entity_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("tagged_items_entity_idx").using("btree", table.entityType.asc().nullsLast().op("text_ops"), table.entityId.asc().nullsLast().op("text_ops")),
	index("tagged_items_tag_id_idx").using("btree", table.tagId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.tagId],
			foreignColumns: [tags.id],
			name: "tagged_items_tag_id_fkey"
		}).onDelete("cascade"),
	unique("tagged_items_tag_id_entity_type_entity_id_key").on(table.entityId, table.entityType, table.tagId),
	pgPolicy("tagged_items_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (EXISTS ( SELECT 1
   FROM tags t
  WHERE ((t.id = tagged_items.tag_id) AND (t.owner_id = app_current_user_id())))))`, withCheck: sql`(app_is_service_role() OR (EXISTS ( SELECT 1
   FROM tags t
  WHERE ((t.id = tagged_items.tag_id) AND (t.owner_id = app_current_user_id())))))`  }),
]);

export const tagShares = pgTable("tag_shares", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	tagId: uuid("tag_id").notNull(),
	sharedWithUserId: uuid("shared_with_user_id").notNull(),
	permission: text().default('read'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("tag_shares_tag_id_idx").using("btree", table.tagId.asc().nullsLast().op("uuid_ops")),
	index("tag_shares_user_id_idx").using("btree", table.sharedWithUserId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.sharedWithUserId],
			foreignColumns: [users.id],
			name: "tag_shares_shared_with_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.tagId],
			foreignColumns: [tags.id],
			name: "tag_shares_tag_id_fkey"
		}).onDelete("cascade"),
	unique("tag_shares_tag_id_shared_with_user_id_key").on(table.sharedWithUserId, table.tagId),
	pgPolicy("tag_shares_select_policy", { as: "permissive", for: "select", to: ["public"], using: sql`(app_is_service_role() OR (shared_with_user_id = app_current_user_id()) OR (EXISTS ( SELECT 1
   FROM tags t
  WHERE ((t.id = tag_shares.tag_id) AND (t.owner_id = app_current_user_id())))))` }),
	pgPolicy("tag_shares_owner_write_policy", { as: "permissive", for: "all", to: ["public"] }),
]);
