import { pgTable, index, foreignKey, unique, pgPolicy, text, uuid, timestamp, check, integer, varchar, uniqueIndex, jsonb, boolean, numeric, date, bigint, primaryKey, pgView, interval, vector, geometry } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * tasks domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
 *   - users
 *   - tasks
 *   - goals
 *   - keyResults
 *   - taskLists
 */

export const users = pgTable("users", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	name: text(),
	avatarUrl: text("avatar_url"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("users_email_lower_idx").using("btree", sql`lower(email)`),
	unique("users_email_key").on(table.email),
	pgPolicy("users_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (id = app_current_user_id()))`  }),
]);

export const tasks = pgTable("tasks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	title: text().notNull(),
	description: text(),
	status: text().default('pending'),
	priority: text().default('medium'),
	dueDate: timestamp("due_date", { withTimezone: true, mode: 'string' }),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: 'string' }),
	parentId: uuid("parent_id"),
	listId: uuid("list_id"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("tasks_open_idx").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.dueDate.asc().nullsLast().op("uuid_ops"), table.priority.asc().nullsLast().op("text_ops")).where(sql`(status = ANY (ARRAY['pending'::text, 'in_progress'::text]))`),
	index("tasks_user_due_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.dueDate.asc().nullsLast().op("uuid_ops")),
	index("tasks_user_status_idx").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.listId],
			foreignColumns: [taskLists.id],
			name: "tasks_list_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.parentId],
			foreignColumns: [table.id],
			name: "tasks_parent_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "tasks_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("tasks_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);

export const goals = pgTable("goals", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	title: text().notNull(),
	description: text(),
	targetDate: timestamp("target_date", { withTimezone: true, mode: 'string' }),
	status: text().default('active'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("goals_user_status_idx").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "goals_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("goals_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);

export const keyResults = pgTable("key_results", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	goalId: uuid("goal_id").notNull(),
	title: text().notNull(),
	targetValue: numeric("target_value", { precision: 10, scale:  2 }),
	currentValue: numeric("current_value", { precision: 10, scale:  2 }),
	unit: text(),
	dueDate: timestamp("due_date", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("key_results_goal_idx").using("btree", table.goalId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.goalId],
			foreignColumns: [goals.id],
			name: "key_results_goal_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("key_results_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (EXISTS ( SELECT 1
   FROM goals g
  WHERE ((g.id = key_results.goal_id) AND (g.user_id = app_current_user_id())))))`, withCheck: sql`(app_is_service_role() OR (EXISTS ( SELECT 1
   FROM goals g
  WHERE ((g.id = key_results.goal_id) AND (g.user_id = app_current_user_id())))))`  }),
]);

export const taskLists = pgTable("task_lists", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	name: text().notNull(),
	color: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("task_lists_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "task_lists_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("task_lists_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);
