#!/usr/bin/env bun
/**
 * Generate domain-specific schema slices from the monolithic migrations/schema.ts
 * 
 * This script creates physically separate schema modules to:
 * - Reduce per-service tsserver workload
 * - Enable targeted type generation
 * - Enforce service boundaries (services only import their domain slice)
 * 
 * Usage:
 *   bun scripts/generate-db-schema-slices.ts
 * 
 * Generated files are committed to the repo (generated artifacts).
 */

import fs from 'fs'
import path from 'path'

// Define domain mappings: which tables belong to each service domain
const DOMAIN_SCHEMAS: Record<string, string[]> = {
  tasks: [
    'users',
    'tasks',
    'goals',
    'keyResults',
    'taskLists',
  ],
  tags: [
    'users',
    'tags',
    'taggedItems',
    'tagShares',
  ],
  calendar: [
    'users',
    'persons',
    'calendarEvents',
    'calendarAttendees',
  ],
  persons: [
    'users',
    'persons',
    'userPersonRelations',
  ],
  bookmarks: [
    'users',
    'bookmarks',
  ],
  possessions: [
    'users',
    'possessions',
    'possessionContainers',
  ],
  finance: [
    'users',
    'financeAccounts',
    'budgetGoals',
    'financialInstitutions',
    'plaidItems',
    'tags',
    'taggedItems',
    'financeTransactions2022',
    'financeTransactions2023',
    'financeTransactions2024',
    'financeTransactions2025',
    'financeTransactions2026',
    'financeTransactionsDefault',
  ],
}

/**
 * Read the monolithic schema file and extract table definitions
 */
function readMonolithicSchema(schemaPath: string): Map<string, string> {
  const content = fs.readFileSync(schemaPath, 'utf-8')
  const lines = content.split('\n')

  const tables = new Map<string, string>()
  let currentTable: string | null = null
  let currentContent: string[] = []
  let nestingLevel = 0

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    // Check if this is an export const table line
    const match = line.match(/export const (\w+)\s*=\s*pgTable\(/)
    if (match) {
      currentTable = match[1]
      currentContent = [line]
      nestingLevel = 1
      continue
    }

    // Collect lines until we close the table definition
    if (currentTable) {
      currentContent.push(line)

      // Track nesting of braces/brackets
      for (const char of line) {
        if (char === '{' || char === '[') nestingLevel++
        if (char === '}' || char === ']') nestingLevel--
      }

      // Table definition ends with `]);` at nesting level 0
      if (nestingLevel === 0 && line.includes(']);')) {
        tables.set(currentTable, currentContent.join('\n'))
        currentTable = null
        currentContent = []
      }
    }
  }

  return tables
}

/**
 * Extract the import statements from the monolithic schema
 */
function getSchemaImports(schemaPath: string): string {
  const content = fs.readFileSync(schemaPath, 'utf-8')
  // Get everything before the first export
  const importSection = content.substring(0, content.indexOf('export const'))
  return importSection.trim()
}

/**
 * Generate a single domain schema file
 */
function generateDomainSchema(
  domainName: string,
  tableNames: string[],
  tableDefinitions: Map<string, string>,
  imports: string
): string {
  const domainTables = tableNames
    .filter(name => tableDefinitions.has(name))
    .map(name => tableDefinitions.get(name)!)
    .join('\n\n')

  if (!domainTables) {
    console.warn(`Warning: No tables found for domain '${domainName}'`)
  }

  return `${imports}

/**
 * ${domainName} domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
${tableNames.map(t => `${tableDefinitions.has(t) ? ' *   - ' + t : ' *   (TODO) - ' + t}`).join('\n')}
 */

${domainTables}
`
}

/**
 * Main generation function
 */
function main() {
  const schemaDir = path.join(process.cwd(), 'packages', 'db', 'src')
  const migrationsPath = path.join(schemaDir, 'migrations', 'schema.ts')
  const outputDir = path.join(schemaDir, 'schema')

  if (!fs.existsSync(migrationsPath)) {
    console.error(`❌ Schema not found: ${migrationsPath}`)
    process.exit(1)
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  console.log('📝 Generating domain schema slices...\n')

  // Read the monolithic schema
  const tables = readMonolithicSchema(migrationsPath)
  const imports = getSchemaImports(migrationsPath)

  let generatedCount = 0

  // Generate each domain schema
  for (const [domainName, tableNames] of Object.entries(DOMAIN_SCHEMAS)) {
    const schemaContent = generateDomainSchema(domainName, tableNames, tables, imports)
    const outputPath = path.join(outputDir, `${domainName}.ts`)

    fs.writeFileSync(outputPath, schemaContent, 'utf-8')
    generatedCount++

    console.log(`✓ Generated: ${path.relative(process.cwd(), outputPath)}`)

    // Validate that generated file doesn't import from migrations/schema.ts
    if (schemaContent.includes('migrations/schema')) {
      console.error(
        `❌ Validation failed: ${domainName}.ts contains imports from migrations/schema.ts`
      )
      process.exit(1)
    }
  }

  console.log(`\n✅ Generated ${generatedCount} domain schema modules`)
  console.log('\n⚠️  Remember to:')
  console.log('   1. Run: bun run typecheck')
  console.log('   2. Review generated files for completeness')
  console.log('   3. Run: git add packages/db/src/schema/*.ts')

  process.exit(0)
}

main()
