export const typingMindBase = {
  data: {
    chats: [],
    folders: [],
    userPrompts: [],
    promptSettings: {},
    userCharacters: [],
    characterSettings: {},
    installedPlugins: [],
    customSearchEngineID: '',
    customSearchAPIKey: '',
    userPluginSettings: {},
    userProfiles: [],
    hiddenButtons: [],
    actionButtonsLabel: false,
    streaming: true,
    automaticTitle: true,
    suggestKeywords: true,
    searchEngine: 'google',
    defaultTemperature: null,
    defaultPresencePenalty: null,
    defaultFrequencyPenalty: null,
    defaultTopP: null,
    defaultTopK: null,
    defaultMaxTokens: null,
    defaultSafetySettings: null,
    defaultPromptCachingEnabled: false,
    defaultContextLimit: 8000,
    modelIDsOrder: [],
    hiddenModelIDs: [],
    keyboardShortcuts: {
      search: 'ctrl+k',
      sidebar: 'ctrl+\\',
      newChat: 'ctrl+n',
      resetChat: 'ctrl+r',
      regenerate: 'ctrl+enter',
      share: 'ctrl+s',
      clearContext: 'ctrl+l',
      togglePlugins: 'ctrl+p',
      copyLastMessage: 'ctrl+c',
    },
    customModels: [],
  },
};

export const validTypingMindInput = {
  data: {
    chats: [
      {
        id: 'chat-1',
        model: 'gpt-4',
        modelInfo: { title: 'GPT-4', id: 'gpt-4' },
        preview: 'Test conversation',
        linkedPlugins: [],
        chatParams: {
          temperature: 0.7,
          presencePenalty: null,
          frequencyPenalty: null,
          topP: null,
          topK: null,
          maxTokens: null,
          safetySettings: null,
          promptCachingEnabled: false,
          contextLimit: 8000,
          streaming: true,
          outputTone: 'professional',
          outputLanguage: 'en',
          outputStyle: 'concise',
          outputFormat: 'text',
          systemMessage: 'You are a helpful assistant.',
        },
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        syncedAt: null,
        chatID: 'chat-1',
        messages: [
          {
            role: 'user' as const,
            content: 'Hello, what can you help me with?',
            createdAt: '2024-01-01T10:00:00Z',
          },
          {
            role: 'assistant' as const,
            content: 'I can help you with various tasks.',
            createdAt: '2024-01-01T10:01:00Z',
          },
        ],
        chatTitle: 'Test Chat',
      },
    ],
    folders: [],
    userPrompts: [],
    promptSettings: {},
    userCharacters: [],
    characterSettings: {},
    installedPlugins: [],
    customSearchEngineID: '',
    customSearchAPIKey: '',
    userPluginSettings: {},
    userProfiles: [],
    hiddenButtons: [],
    actionButtonsLabel: false,
    streaming: true,
    automaticTitle: true,
    suggestKeywords: true,
    searchEngine: 'google',
    defaultTemperature: null,
    defaultPresencePenalty: null,
    defaultFrequencyPenalty: null,
    defaultTopP: null,
    defaultTopK: null,
    defaultMaxTokens: null,
    defaultSafetySettings: null,
    defaultPromptCachingEnabled: false,
    defaultContextLimit: 8000,
    modelIDsOrder: [],
    hiddenModelIDs: [],
    keyboardShortcuts: {
      search: 'ctrl+k',
      sidebar: 'ctrl+\\',
      newChat: 'ctrl+n',
      resetChat: 'ctrl+r',
      regenerate: 'ctrl+enter',
      share: 'ctrl+s',
      clearContext: 'ctrl+l',
      togglePlugins: 'ctrl+p',
      copyLastMessage: 'ctrl+c',
    },
    customModels: [],
  },
};
